namespace Scripts.Spells.Rogue;

public enum CheatDeath
{
	SPELL_ROGUE_CHEAT_DEATH = 31230,
	SPELL_ROGUE_CHEAT_DEATH_ANIM = 31231,
	SPELL_ROGUE_CHEAT_DEATH_DMG_REDUC = 45182,
	SPELL_ROGUE_CHEAT_DEATH_CD_AURA = 45181
}