// Copyright (c) Forged WoW LLC <https://github.com/ForgedWoW/ForgedCore>
// Licensed under GPL-3.0 license. See <https://github.com/ForgedWoW/ForgedCore/blob/master/LICENSE> for full information.

namespace Scripts.Spells.Monk;

public enum CracklingJade
{
	SPELL_MONK_CRACKLING_JADE_LIGHTNING = 117952,
	SPELL_MONK_CRACKLING_JADE_LIGHTNING_CHI_PROC_DRIVER = 123332,
	SPELL_MONK_CRACKLING_JADE_LIGHTNING_KNOCK_BACK_DRIVER = 117959,
	SPELL_MONK_CRACKLING_JADE_LIGHTNING_KNOCK_BACK = 117962,
	SPELL_MONK_CRACKLING_JADE_LIGHTNING_TALENT = 125648,
	SPELL_MONK_CRACKLING_JAD_LIGHTNING_TALENT_SPEED = 125647
}