// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: bgs/low/pb/client/attribute_types.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Bgs.Protocol {

  /// <summary>Holder for reflection information generated from bgs/low/pb/client/attribute_types.proto</summary>
  public static partial class AttributeTypesReflection {

    #region Descriptor
    /// <summary>File descriptor for bgs/low/pb/client/attribute_types.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AttributeTypesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CidiZ3MvbG93L3BiL2NsaWVudC9hdHRyaWJ1dGVfdHlwZXMucHJvdG8SDGJn",
            "cy5wcm90b2NvbBokYmdzL2xvdy9wYi9jbGllbnQvZW50aXR5X3R5cGVzLnBy",
            "b3RvIuEBCgdWYXJpYW50EhIKCmJvb2xfdmFsdWUYAiABKAgSEQoJaW50X3Zh",
            "bHVlGAMgASgDEhMKC2Zsb2F0X3ZhbHVlGAQgASgBEhQKDHN0cmluZ192YWx1",
            "ZRgFIAEoCRISCgpibG9iX3ZhbHVlGAYgASgMEhUKDW1lc3NhZ2VfdmFsdWUY",
            "ByABKAwSFAoMZm91cmNjX3ZhbHVlGAggASgJEhIKCnVpbnRfdmFsdWUYCSAB",
            "KAQSLwoPZW50aXR5X2lkX3ZhbHVlGAogASgLMhYuYmdzLnByb3RvY29sLkVu",
            "dGl0eUlkIj8KCUF0dHJpYnV0ZRIMCgRuYW1lGAEgAigJEiQKBXZhbHVlGAIg",
            "AigLMhUuYmdzLnByb3RvY29sLlZhcmlhbnQi1gEKD0F0dHJpYnV0ZUZpbHRl",
            "chI/CgJvcBgBIAIoDjInLmJncy5wcm90b2NvbC5BdHRyaWJ1dGVGaWx0ZXIu",
            "T3BlcmF0aW9uOgpNQVRDSF9OT05FEioKCWF0dHJpYnV0ZRgCIAMoCzIXLmJn",
            "cy5wcm90b2NvbC5BdHRyaWJ1dGUiVgoJT3BlcmF0aW9uEg4KCk1BVENIX05P",
            "TkUQABINCglNQVRDSF9BTlkQARINCglNQVRDSF9BTEwQAhIbChdNQVRDSF9B",
            "TExfTU9TVF9TUEVDSUZJQxADQh8KDWJuZXQucHJvdG9jb2xCDkF0dHJpYnV0",
            "ZVByb3Rv"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Bgs.Protocol.EntityTypesReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Bgs.Protocol.Variant), global::Bgs.Protocol.Variant.Parser, new[]{ "BoolValue", "IntValue", "FloatValue", "StringValue", "BlobValue", "MessageValue", "FourccValue", "UintValue", "EntityIdValue" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bgs.Protocol.Attribute), global::Bgs.Protocol.Attribute.Parser, new[]{ "Name", "Value" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bgs.Protocol.AttributeFilter), global::Bgs.Protocol.AttributeFilter.Parser, new[]{ "Op", "Attribute" }, null, new[]{ typeof(global::Bgs.Protocol.AttributeFilter.Types.Operation) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Variant : pb::IMessage<Variant> {
    private static readonly pb::MessageParser<Variant> _parser = new pb::MessageParser<Variant>(() => new Variant());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Variant> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bgs.Protocol.AttributeTypesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Variant() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Variant(Variant other) : this() {
      _hasBits0 = other._hasBits0;
      boolValue_ = other.boolValue_;
      intValue_ = other.intValue_;
      floatValue_ = other.floatValue_;
      stringValue_ = other.stringValue_;
      blobValue_ = other.blobValue_;
      messageValue_ = other.messageValue_;
      fourccValue_ = other.fourccValue_;
      uintValue_ = other.uintValue_;
      entityIdValue_ = other.HasEntityIdValue ? other.entityIdValue_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Variant Clone() {
      return new Variant(this);
    }

    /// <summary>Field number for the "bool_value" field.</summary>
    public const int BoolValueFieldNumber = 2;
    private readonly static bool BoolValueDefaultValue = false;

    private bool boolValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool BoolValue {
      get { if ((_hasBits0 & 1) != 0) { return boolValue_; } else { return BoolValueDefaultValue; } }
      set {
        _hasBits0 |= 1;
        boolValue_ = value;
      }
    }
    /// <summary>Gets whether the "bool_value" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasBoolValue {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "bool_value" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearBoolValue() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "int_value" field.</summary>
    public const int IntValueFieldNumber = 3;
    private readonly static long IntValueDefaultValue = 0L;

    private long intValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long IntValue {
      get { if ((_hasBits0 & 2) != 0) { return intValue_; } else { return IntValueDefaultValue; } }
      set {
        _hasBits0 |= 2;
        intValue_ = value;
      }
    }
    /// <summary>Gets whether the "int_value" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasIntValue {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "int_value" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearIntValue() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "float_value" field.</summary>
    public const int FloatValueFieldNumber = 4;
    private readonly static double FloatValueDefaultValue = 0D;

    private double floatValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double FloatValue {
      get { if ((_hasBits0 & 4) != 0) { return floatValue_; } else { return FloatValueDefaultValue; } }
      set {
        _hasBits0 |= 4;
        floatValue_ = value;
      }
    }
    /// <summary>Gets whether the "float_value" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasFloatValue {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "float_value" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearFloatValue() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "string_value" field.</summary>
    public const int StringValueFieldNumber = 5;
    private readonly static string StringValueDefaultValue = "";

    private string stringValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StringValue {
      get { return stringValue_ ?? StringValueDefaultValue; }
      set {
        stringValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "string_value" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasStringValue {
      get { return stringValue_ != null; }
    }
    /// <summary>Clears the value of the "string_value" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearStringValue() {
      stringValue_ = null;
    }

    /// <summary>Field number for the "blob_value" field.</summary>
    public const int BlobValueFieldNumber = 6;
    private readonly static pb::ByteString BlobValueDefaultValue = pb::ByteString.Empty;

    private pb::ByteString blobValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString BlobValue {
      get { return blobValue_ ?? BlobValueDefaultValue; }
      set {
        blobValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "blob_value" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasBlobValue {
      get { return blobValue_ != null; }
    }
    /// <summary>Clears the value of the "blob_value" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearBlobValue() {
      blobValue_ = null;
    }

    /// <summary>Field number for the "message_value" field.</summary>
    public const int MessageValueFieldNumber = 7;
    private readonly static pb::ByteString MessageValueDefaultValue = pb::ByteString.Empty;

    private pb::ByteString messageValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString MessageValue {
      get { return messageValue_ ?? MessageValueDefaultValue; }
      set {
        messageValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "message_value" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasMessageValue {
      get { return messageValue_ != null; }
    }
    /// <summary>Clears the value of the "message_value" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMessageValue() {
      messageValue_ = null;
    }

    /// <summary>Field number for the "fourcc_value" field.</summary>
    public const int FourccValueFieldNumber = 8;
    private readonly static string FourccValueDefaultValue = "";

    private string fourccValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FourccValue {
      get { return fourccValue_ ?? FourccValueDefaultValue; }
      set {
        fourccValue_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "fourcc_value" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasFourccValue {
      get { return fourccValue_ != null; }
    }
    /// <summary>Clears the value of the "fourcc_value" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearFourccValue() {
      fourccValue_ = null;
    }

    /// <summary>Field number for the "uint_value" field.</summary>
    public const int UintValueFieldNumber = 9;
    private readonly static ulong UintValueDefaultValue = 0UL;

    private ulong uintValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong UintValue {
      get { if ((_hasBits0 & 8) != 0) { return uintValue_; } else { return UintValueDefaultValue; } }
      set {
        _hasBits0 |= 8;
        uintValue_ = value;
      }
    }
    /// <summary>Gets whether the "uint_value" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasUintValue {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "uint_value" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearUintValue() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "entity_id_value" field.</summary>
    public const int EntityIdValueFieldNumber = 10;
    private global::Bgs.Protocol.EntityId entityIdValue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Bgs.Protocol.EntityId EntityIdValue {
      get { return entityIdValue_; }
      set {
        entityIdValue_ = value;
      }
    }
    /// <summary>Gets whether the entity_id_value field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasEntityIdValue {
      get { return entityIdValue_ != null; }
    }
    /// <summary>Clears the value of the entity_id_value field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearEntityIdValue() {
      entityIdValue_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Variant);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Variant other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BoolValue != other.BoolValue) return false;
      if (IntValue != other.IntValue) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(FloatValue, other.FloatValue)) return false;
      if (StringValue != other.StringValue) return false;
      if (BlobValue != other.BlobValue) return false;
      if (MessageValue != other.MessageValue) return false;
      if (FourccValue != other.FourccValue) return false;
      if (UintValue != other.UintValue) return false;
      if (!object.Equals(EntityIdValue, other.EntityIdValue)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasBoolValue) hash ^= BoolValue.GetHashCode();
      if (HasIntValue) hash ^= IntValue.GetHashCode();
      if (HasFloatValue) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(FloatValue);
      if (HasStringValue) hash ^= StringValue.GetHashCode();
      if (HasBlobValue) hash ^= BlobValue.GetHashCode();
      if (HasMessageValue) hash ^= MessageValue.GetHashCode();
      if (HasFourccValue) hash ^= FourccValue.GetHashCode();
      if (HasUintValue) hash ^= UintValue.GetHashCode();
      if (HasEntityIdValue) hash ^= EntityIdValue.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (HasBoolValue) {
        output.WriteRawTag(16);
        output.WriteBool(BoolValue);
      }
      if (HasIntValue) {
        output.WriteRawTag(24);
        output.WriteInt64(IntValue);
      }
      if (HasFloatValue) {
        output.WriteRawTag(33);
        output.WriteDouble(FloatValue);
      }
      if (HasStringValue) {
        output.WriteRawTag(42);
        output.WriteString(StringValue);
      }
      if (HasBlobValue) {
        output.WriteRawTag(50);
        output.WriteBytes(BlobValue);
      }
      if (HasMessageValue) {
        output.WriteRawTag(58);
        output.WriteBytes(MessageValue);
      }
      if (HasFourccValue) {
        output.WriteRawTag(66);
        output.WriteString(FourccValue);
      }
      if (HasUintValue) {
        output.WriteRawTag(72);
        output.WriteUInt64(UintValue);
      }
      if (HasEntityIdValue) {
        output.WriteRawTag(82);
        output.WriteMessage(EntityIdValue);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasBoolValue) {
        size += 1 + 1;
      }
      if (HasIntValue) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(IntValue);
      }
      if (HasFloatValue) {
        size += 1 + 8;
      }
      if (HasStringValue) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StringValue);
      }
      if (HasBlobValue) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(BlobValue);
      }
      if (HasMessageValue) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(MessageValue);
      }
      if (HasFourccValue) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FourccValue);
      }
      if (HasUintValue) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(UintValue);
      }
      if (HasEntityIdValue) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EntityIdValue);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Variant other) {
      if (other == null) {
        return;
      }
      if (other.HasBoolValue) {
        BoolValue = other.BoolValue;
      }
      if (other.HasIntValue) {
        IntValue = other.IntValue;
      }
      if (other.HasFloatValue) {
        FloatValue = other.FloatValue;
      }
      if (other.HasStringValue) {
        StringValue = other.StringValue;
      }
      if (other.HasBlobValue) {
        BlobValue = other.BlobValue;
      }
      if (other.HasMessageValue) {
        MessageValue = other.MessageValue;
      }
      if (other.HasFourccValue) {
        FourccValue = other.FourccValue;
      }
      if (other.HasUintValue) {
        UintValue = other.UintValue;
      }
      if (other.HasEntityIdValue) {
        if (!HasEntityIdValue) {
          EntityIdValue = new global::Bgs.Protocol.EntityId();
        }
        EntityIdValue.MergeFrom(other.EntityIdValue);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 16: {
            BoolValue = input.ReadBool();
            break;
          }
          case 24: {
            IntValue = input.ReadInt64();
            break;
          }
          case 33: {
            FloatValue = input.ReadDouble();
            break;
          }
          case 42: {
            StringValue = input.ReadString();
            break;
          }
          case 50: {
            BlobValue = input.ReadBytes();
            break;
          }
          case 58: {
            MessageValue = input.ReadBytes();
            break;
          }
          case 66: {
            FourccValue = input.ReadString();
            break;
          }
          case 72: {
            UintValue = input.ReadUInt64();
            break;
          }
          case 82: {
            if (!HasEntityIdValue) {
              EntityIdValue = new global::Bgs.Protocol.EntityId();
            }
            input.ReadMessage(EntityIdValue);
            break;
          }
        }
      }
    }

  }

  public sealed partial class Attribute : pb::IMessage<Attribute> {
    private static readonly pb::MessageParser<Attribute> _parser = new pb::MessageParser<Attribute>(() => new Attribute());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Attribute> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bgs.Protocol.AttributeTypesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Attribute() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Attribute(Attribute other) : this() {
      name_ = other.name_;
      value_ = other.HasValue ? other.value_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Attribute Clone() {
      return new Attribute(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private readonly static string NameDefaultValue = "";

    private string name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_ ?? NameDefaultValue; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearName() {
      name_ = null;
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 2;
    private global::Bgs.Protocol.Variant value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Bgs.Protocol.Variant Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }
    /// <summary>Gets whether the value field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasValue {
      get { return value_ != null; }
    }
    /// <summary>Clears the value of the value field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearValue() {
      value_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Attribute);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Attribute other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (!object.Equals(Value, other.Value)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasName) hash ^= Name.GetHashCode();
      if (HasValue) hash ^= Value.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (HasName) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (HasValue) {
        output.WriteRawTag(18);
        output.WriteMessage(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (HasValue) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Value);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Attribute other) {
      if (other == null) {
        return;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.HasValue) {
        if (!HasValue) {
          Value = new global::Bgs.Protocol.Variant();
        }
        Value.MergeFrom(other.Value);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            if (!HasValue) {
              Value = new global::Bgs.Protocol.Variant();
            }
            input.ReadMessage(Value);
            break;
          }
        }
      }
    }

  }

  public sealed partial class AttributeFilter : pb::IMessage<AttributeFilter> {
    private static readonly pb::MessageParser<AttributeFilter> _parser = new pb::MessageParser<AttributeFilter>(() => new AttributeFilter());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AttributeFilter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bgs.Protocol.AttributeTypesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AttributeFilter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AttributeFilter(AttributeFilter other) : this() {
      _hasBits0 = other._hasBits0;
      op_ = other.op_;
      attribute_ = other.attribute_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AttributeFilter Clone() {
      return new AttributeFilter(this);
    }

    /// <summary>Field number for the "op" field.</summary>
    public const int OpFieldNumber = 1;
    private readonly static global::Bgs.Protocol.AttributeFilter.Types.Operation OpDefaultValue = global::Bgs.Protocol.AttributeFilter.Types.Operation.MatchNone;

    private global::Bgs.Protocol.AttributeFilter.Types.Operation op_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Bgs.Protocol.AttributeFilter.Types.Operation Op {
      get { if ((_hasBits0 & 1) != 0) { return op_; } else { return OpDefaultValue; } }
      set {
        _hasBits0 |= 1;
        op_ = value;
      }
    }
    /// <summary>Gets whether the "op" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasOp {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "op" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearOp() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "attribute" field.</summary>
    public const int AttributeFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Bgs.Protocol.Attribute> _repeated_attribute_codec
        = pb::FieldCodec.ForMessage(18, global::Bgs.Protocol.Attribute.Parser);
    private readonly pbc::RepeatedField<global::Bgs.Protocol.Attribute> attribute_ = new pbc::RepeatedField<global::Bgs.Protocol.Attribute>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Bgs.Protocol.Attribute> Attribute {
      get { return attribute_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AttributeFilter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AttributeFilter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Op != other.Op) return false;
      if(!attribute_.Equals(other.attribute_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasOp) hash ^= Op.GetHashCode();
      hash ^= attribute_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (HasOp) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Op);
      }
      attribute_.WriteTo(output, _repeated_attribute_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasOp) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Op);
      }
      size += attribute_.CalculateSize(_repeated_attribute_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AttributeFilter other) {
      if (other == null) {
        return;
      }
      if (other.HasOp) {
        Op = other.Op;
      }
      attribute_.Add(other.attribute_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Op = (global::Bgs.Protocol.AttributeFilter.Types.Operation) input.ReadEnum();
            break;
          }
          case 18: {
            attribute_.AddEntriesFrom(input, _repeated_attribute_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the AttributeFilter message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Operation {
        [pbr::OriginalName("MATCH_NONE")] MatchNone = 0,
        [pbr::OriginalName("MATCH_ANY")] MatchAny = 1,
        [pbr::OriginalName("MATCH_ALL")] MatchAll = 2,
        [pbr::OriginalName("MATCH_ALL_MOST_SPECIFIC")] MatchAllMostSpecific = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
