ALTER TABLE `broadcast_text`
	ADD COLUMN `Type` SMALLINT UNSIGNED NOT NULL DEFAULT '0' AFTER `EmoteDelay2`,
	ADD COLUMN `PlayerConditionID` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0' AFTER `SoundID`,
	CHANGE COLUMN `VerifiedBuild` `VerifiedBuild` SMALLINT(5) NULL DEFAULT '0' AFTER `PlayerConditionID`,
DROP COLUMN `UnkMoP1`,
DROP COLUMN `UnkMoP2`;
