/*
 * Copyright (C) 2012-2019 CypherCore <http://github.com/CypherCore>
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
using System;

namespace Framework.Constants
{
    public enum DB2ColumnCompression : uint
    {
        None,
        Immediate,
        Common,
        Pallet,
        PalletArray,
        SignedImmediate
    }

    [Flags]
    public enum HeaderFlags : short
    {
        None = 0x0,
        OffsetMap = 0x1,
        SecondIndex = 0x2,
        IndexMap = 0x4,
        Unknown = 0x8,
        Compressed = 0x10,
    }

    public enum AbilityLearnType : byte
    {
        OnSkillValue = 1, // Spell state will update depending on skill value
        OnSkillLearn = 2  // Spell will be learned/removed together with entire skill
    }

    public enum Anim
    {
        Stand = 0,
        Death = 1,
        Spell = 2,
        Stop = 3,
        Walk = 4,
        Run = 5,
        Dead = 6,
        Rise = 7,
        StandWound = 8,
        CombatWound = 9,
        CombatCritical = 10,
        ShuffleLeft = 11,
        ShuffleRight = 12,
        WalkBackwards = 13,
        Stun = 14,
        HandsClosed = 15,
        AttackUnarmed = 16,
        Attack1h = 17,
        Attack2h = 18,
        Attack2hl = 19,
        ParryUnarmed = 20,
        Parry1h = 21,
        Parry2h = 22,
        Parry2hl = 23,
        ShieldBlock = 24,
        ReadyUnarmed = 25,
        Ready1h = 26,
        Ready2h = 27,
        Ready2hl = 28,
        ReadyBow = 29,
        Dodge = 30,
        SpellPrecast = 31,
        SpellCast = 32,
        SpellCastArea = 33,
        NpcWelcome = 34,
        NpcGoodbye = 35,
        Block = 36,
        JumpStart = 37,
        Jump = 38,
        JumpEnd = 39,
        Fall = 40,
        SwimIdle = 41,
        Swim = 42,
        SwimLeft = 43,
        SwimRight = 44,
        SwimBackwards = 45,
        AttackBow = 46,
        FireBow = 47,
        ReadyRifle = 48,
        AttackRifle = 49,
        Loot = 50,
        ReadySpellDirected = 51,
        ReadySpellOmni = 52,
        SpellCastDirected = 53,
        SpellCastOmni = 54,
        BattleRoar = 55,
        ReadyAbility = 56,
        Special1h = 57,
        Special2h = 58,
        ShieldBash = 59,
        EmoteTalk = 60,
        EmoteEat = 61,
        EmoteWork = 62,
        EmoteUseStanding = 63,
        EmoteTalkExclamation = 64,
        EmoteTalkQuestion = 65,
        EmoteBow = 66,
        EmoteWave = 67,
        EmoteCheer = 68,
        EmoteDance = 69,
        EmoteLaugh = 70,
        EmoteSleep = 71,
        EmoteSitGround = 72,
        EmoteRude = 73,
        EmoteRoar = 74,
        EmoteKneel = 75,
        EmoteKiss = 76,
        EmoteCry = 77,
        EmoteChicken = 78,
        EmoteBeg = 79,
        EmoteApplaud = 80,
        EmoteShout = 81,
        EmoteFlex = 82,
        EmoteShy = 83,
        EmotePoint = 84,
        Attack1hPierce = 85,
        Attack2hLoosePierce = 86,
        AttackOff = 87,
        AttackOffPierce = 88,
        Sheathe = 89,
        HipSheathe = 90,
        Mount = 91,
        RunRight = 92,
        RunLeft = 93,
        MountSpecial = 94,
        Kick = 95,
        SitGroundDown = 96,
        SitGround = 97,
        SitGroundUp = 98,
        SleepDown = 99,
        Sleep = 100,
        SleepUp = 101,
        SitChairLow = 102,
        SitChairMed = 103,
        SitChairHigh = 104,
        LoadBow = 105,
        LoadRifle = 106,
        AttackThrown = 107,
        ReadyThrown = 108,
        HoldBow = 109,
        HoldRifle = 110,
        HoldThrown = 111,
        LoadThrown = 112,
        EmoteSalute = 113,
        KneelStart = 114,
        KneelLoop = 115,
        KneelEnd = 116,
        AttackUnarmedOff = 117,
        SpecialUnarmed = 118,
        StealthWalk = 119,
        StealthStand = 120,
        Knockdown = 121,
        EatingLoop = 122,
        UseStandingLoop = 123,
        ChannelCastDirected = 124,
        ChannelCastOmni = 125,
        Whirlwind = 126,
        Birth = 127,
        UseStandingStart = 128,
        UseStandingEnd = 129,
        CreatureSpecial = 130,
        Drown = 131,
        Drowned = 132,
        FishingCast = 133,
        FishingLoop = 134,
        Fly = 135,
        EmoteWorkNoSheathe = 136,
        EmoteStunNoSheathe = 137,
        EmoteUseStandingNoSheathe = 138,
        SpellSleepDown = 139,
        SpellKneelStart = 140,
        SpellKneelLoop = 141,
        SpellKneelEnd = 142,
        Sprint = 143,
        InFlight = 144,
        Spawn = 145,
        Close = 146,
        Closed = 147,
        Open = 148,
        Opened = 149,
        Destroy = 150,
        Destroyed = 151,
        Rebuild = 152,
        Custom0 = 153,
        Custom1 = 154,
        Custom2 = 155,
        Custom3 = 156,
        Despawn = 157,
        Hold = 158,
        Decay = 159,
        BowPull = 160,
        BowRelease = 161,
        ShipStart = 162,
        ShipMoving = 163,
        ShipStop = 164,
        GroupArrow = 165,
        Arrow = 166,
        CorpseArrow = 167,
        GuideArrow = 168,
        Sway = 169,
        DruidCatPounce = 170,
        DruidCatRip = 171,
        DruidCatRake = 172,
        DruidCatRavage = 173,
        DruidCatClaw = 174,
        DruidCatCower = 175,
        DruidBearSwipe = 176,
        DruidBearBite = 177,
        DruidBearMaul = 178,
        DruidBearBash = 179,
        DragonTail = 180,
        DragonStomp = 181,
        DragonSpit = 182,
        DragonSpitHover = 183,
        DragonSpitFly = 184,
        EmoteYes = 185,
        EmoteNo = 186,
        JumpLandRun = 187,
        LootHold = 188,
        LootUp = 189,
        StandHigh = 190,
        Impact = 191,
        Liftoff = 192,
        Hover = 193,
        SuccubusEntice = 194,
        EmoteTrain = 195,
        EmoteDead = 196,
        EmoteDanceOnce = 197,
        Deflect = 198,
        EmoteEatNoSheathe = 199,
        Land = 200,
        Submerge = 201,
        Submerged = 202,
        Cannibalize = 203,
        ArrowBirth = 204,
        GroupArrowBirth = 205,
        CorpseArrowBirth = 206,
        GuideArrowBirth = 207,
        EmoteTalkNoSheathe = 208,
        EmotePointNoSheathe = 209,
        EmoteSaluteNoSheathe = 210,
        EmoteDanceSpecial = 211,
        Mutilate = 212,
        CustomSpell01 = 213,
        CustomSpell02 = 214,
        CustomSpell03 = 215,
        CustomSpell04 = 216,
        CustomSpell05 = 217,
        CustomSpell06 = 218,
        CustomSpell07 = 219,
        CustomSpell08 = 220,
        CustomSpell09 = 221,
        CustomSpell10 = 222,
        StealthRun = 223,
        Emerge = 224,
        Cower = 225,
        Grab = 226,
        GrabClosed = 227,
        GrabThrown = 228,
        FlyStand = 229,
        FlyDeath = 230,
        FlySpell = 231,
        FlyStop = 232,
        FlyWalk = 233,
        FlyRun = 234,
        FlyDead = 235,
        FlyRise = 236,
        FlyStandWound = 237,
        FlyCombatWound = 238,
        FlyCombatCritical = 239,
        FlyShuffleLeft = 240,
        FlyShuffleRight = 241,
        FlyWalkBackwards = 242,
        FlyStun = 243,
        FlyHandsClosed = 244,
        FlyAttackUnarmed = 245,
        FlyAttack1h = 246,
        FlyAttack2h = 247,
        FlyAttack2hl = 248,
        FlyParryUnarmed = 249,
        FlyParry1h = 250,
        FlyParry2h = 251,
        FlyParry2hl = 252,
        FlyShieldBlock = 253,
        FlyReadyUnarmed = 254,
        FlyReady1h = 255,
        FlyReady2h = 256,
        FlyReady2hl = 257,
        FlyReadyBow = 258,
        FlyDodge = 259,
        FlySpellPrecast = 260,
        FlySpellCast = 261,
        FlySpellCastArea = 262,
        FlyNpcWelcome = 263,
        FlyNpcGoodbye = 264,
        FlyBlock = 265,
        FlyJumpStart = 266,
        FlyJump = 267,
        FlyJumpEnd = 268,
        FlyFall = 269,
        FlySwimIdle = 270,
        FlySwim = 271,
        FlySwimLeft = 272,
        FlySwimRight = 273,
        FlySwimBackwards = 274,
        FlyAttackBow = 275,
        FlyFireBow = 276,
        FlyReadyRifle = 277,
        FlyAttackRifle = 278,
        FlyLoot = 279,
        FlyReadySpellDirected = 280,
        FlyReadySpellOmni = 281,
        FlySpellCastDirected = 282,
        FlySpellCastOmni = 283,
        FlySpellBattleRoar = 284,
        FlyReadyAbility = 285,
        FlySpecial1h = 286,
        FlySpecial2h = 287,
        FlyShieldBash = 288,
        FlyEmoteTalk = 289,
        FlyEmoteEat = 290,
        FlyEmoteWork = 291,
        FlyUseStanding = 292,
        FlyEmoteTalkExclamation = 293,
        FlyEmoteTalkQuestion = 294,
        FlyEmoteBow = 295,
        FlyEmoteWave = 296,
        FlyEmoteCheer = 297,
        FlyEmoteDance = 298,
        FlyEmoteLaugh = 299,
        FlyEmoteSleep = 300,
        FlyEmoteSitGround = 301,
        FlyEmoteRude = 302,
        FlyEmoteRoar = 303,
        FlyEmoteKneel = 304,
        FlyEmoteKiss = 305,
        FlyEmoteCry = 306,
        FlyEmoteChicken = 307,
        FlyEmoteBeg = 308,
        FlyEmoteApplaud = 309,
        FlyEmoteShout = 310,
        FlyEmoteFlex = 311,
        FlyEmoteShy = 312,
        FlyEmotePoint = 313,
        FlyAttack1hPierce = 314,
        FlyAttack2hLoosePierce = 315,
        FlyAttackOff = 316,
        FlyAttackOffPierce = 317,
        FlySheath = 318,
        FlyHipSheath = 319,
        FlyMount = 320,
        FlyRunRight = 321,
        FlyRunLeft = 322,
        FlyMountSpecial = 323,
        FlyKick = 324,
        FlySitGroundDown = 325,
        FlySitGround = 326,
        FlySitGroundUp = 327,
        FlySleepDown = 328,
        FlySleep = 329,
        FlySleepUp = 330,
        FlySitChairLow = 331,
        FlySitChairMed = 332,
        FlySitChairHigh = 333,
        FlyLoadBow = 334,
        FlyLoadRifle = 335,
        FlyAttackThrown = 336,
        FlyReadyThrown = 337,
        FlyHoldBow = 338,
        FlyHoldRifle = 339,
        FlyHoldThrown = 340,
        FlyLoadThrown = 341,
        FlyEmoteSalute = 342,
        FlyKneelStart = 343,
        FlyKneelLoop = 344,
        FlyKneelEnd = 345,
        FlyAttackUnarmedOff = 346,
        FlySpecialUnarmed = 347,
        FlyStealthWalk = 348,
        FlyStealthStand = 349,
        FlyKnockdown = 350,
        FlyEatingLoop = 351,
        FlyUseStandingLoop = 352,
        FlyChannelCastDirected = 353,
        FlyChannelCastOmni = 354,
        FlyWhirlwind = 355,
        FlyBirth = 356,
        FlyUseStandingStart = 357,
        FlyUseStandingEnd = 358,
        FlyCreatureSpecial = 359,
        FlyDrown = 360,
        FlyDrowned = 361,
        FlyFishingCast = 362,
        FlyFishingLoop = 363,
        FlyFly = 364,
        FlyEmoteWorkNoSheathe = 365,
        FlyEmoteStunNoSheathe = 366,
        FlyEmoteUseStandingNoSheathe = 367,
        FlySpellSleepDown = 368,
        FlySpellKneelStart = 369,
        FlySpellKneelLoop = 370,
        FlySpellKneelEnd = 371,
        FlySprint = 372,
        FlyInFlight = 373,
        FlySpawn = 374,
        FlyClose = 375,
        FlyClosed = 376,
        FlyOpen = 377,
        FlyOpened = 378,
        FlyDestroy = 379,
        FlyDestroyed = 380,
        FlyRebuild = 381,
        FlyCustom0 = 382,
        FlyCustom1 = 383,
        FlyCustom2 = 384,
        FlyCustom3 = 385,
        FlyDespawn = 386,
        FlyHold = 387,
        FlyDecay = 388,
        FlyBowPull = 389,
        FlyBowRelease = 390,
        FlyShipStart = 391,
        FlyShipMoving = 392,
        FlyShipStop = 393,
        FlyGroupArrow = 394,
        FlyArrow = 395,
        FlyCorpseArrow = 396,
        FlyGuideArrow = 397,
        FlySway = 398,
        FlyDruidCatPounce = 399,
        FlyDruidCatRip = 400,
        FlyDruidCatRake = 401,
        FlyDruidCatRavage = 402,
        FlyDruidCatClaw = 403,
        FlyDruidCatCower = 404,
        FlyDruidBearSwipe = 405,
        FlyDruidBearBite = 406,
        FlyDruidBearMaul = 407,
        FlyDruidBearBash = 408,
        FlyDragonTail = 409,
        FlyDragonStomp = 410,
        FlyDragonSpit = 411,
        FlyDragonSpitHover = 412,
        FlyDragonSpitFly = 413,
        FlyEmoteYes = 414,
        FlyEmoteNo = 415,
        FlyJumpLandRun = 416,
        FlyLootHold = 417,
        FlyLootUp = 418,
        FlyStandHigh = 419,
        FlyImpact = 420,
        FlyLiftoff = 421,
        FlyHover = 422,
        FlySuccubusEntice = 423,
        FlyEmoteTrain = 424,
        FlyEmoteDead = 425,
        FlyEmoteDanceOnce = 426,
        FlyDeflect = 427,
        FlyEmoteEatNoSheathe = 428,
        FlyLand = 429,
        FlySubmerge = 430,
        FlySubmerged = 431,
        FlyCannibalize = 432,
        FlyArrowBirth = 433,
        FlyGroupArrowBirth = 434,
        FlyCorpseArrowBirth = 435,
        FlyGuideArrowBirth = 436,
        FlyEmoteTalkNoSheathe = 437,
        FlyEmotePointNoSheathe = 438,
        FlyEmoteSaluteNoSheathe = 439,
        FlyEmoteDanceSpecial = 440,
        FlyMutilate = 441,
        FlyCustomSpell01 = 442,
        FlyCustomSpell02 = 443,
        FlyCustomSpell03 = 444,
        FlyCustomSpell04 = 445,
        FlyCustomSpell05 = 446,
        FlyCustomSpell06 = 447,
        FlyCustomSpell07 = 448,
        FlyCustomSpell08 = 449,
        FlyCustomSpell09 = 450,
        FlyCustomSpell10 = 451,
        FlyStealthRun = 452,
        FlyEmerge = 453,
        FlyCower = 454,
        FlyGrab = 455,
        FlyGrabClosed = 456,
        FlyGrabThrown = 457,
        ToFly = 458,
        ToHover = 459,
        ToGround = 460,
        FlyToFly = 461,
        FlyToHover = 462,
        FlyToGround = 463,
        Settle = 464,
        FlySettle = 465,
        DeathStart = 466,
        DeathLoop = 467,
        DeathEnd = 468,
        FlyDeathStart = 469,
        FlyDeathLoop = 470,
        FlyDeathEnd = 471,
        DeathEndHold = 472,
        FlyDeathEndHold = 473,
        Strangulate = 474,
        FlyStrangulate = 475,
        ReadyJoust = 476,
        LoadJoust = 477,
        HoldJoust = 478,
        FlyReadyJoust = 479,
        FlyLoadJoust = 480,
        FlyHoldJoust = 481,
        AttackJoust = 482,
        FlyAttackJoust = 483,
        ReclinedMount = 484,
        FlyReclinedMount = 485,
        ToAltered = 486,
        FromAltered = 487,
        FlyToAltered = 488,
        FlyFromAltered = 489,
        InStocks = 490,
        FlyInStocks = 491,
        VehicleGrab = 492,
        VehicleThrow = 493,
        FlyVehicleGrab = 494,
        FlyVehicleThrow = 495,
        ToAlteredPostSwap = 496,
        FromAlteredPostSwap = 497,
        FlyToAlteredPostSwap = 498,
        FlyFromAlteredPostSwap = 499,
        ReclinedMountPassenger = 500,
        FlyReclinedMountPassenger = 501,
        Carry2h = 502,
        Carried2h = 503,
        FlyCarry2h = 504,
        FlyCarried2h = 505,
        EmoteSniff = 506,
        EmoteFlySniff = 507,
        AttackFist1h = 508,
        FlyAttackFist1h = 509,
        AttackFist1hOff = 510,
        FlyAttackFist1hOff = 511,
        ParryFist1h = 512,
        FlyParryFist1h = 513,
        ReadyFist1h = 514,
        FlyReadyFist1h = 515,
        SpecialFist1h = 516,
        FlySpecialFist1h = 517,
        EmoteReadStart = 518,
        FlyEmoteReadStart = 519,
        EmoteReadLoop = 520,
        FlyEmoteReadLoop = 521,
        EmoteReadEnd = 522,
        FlyEmoteReadEnd = 523,
        SwimRun = 524,
        FlySwimRun = 525,
        SwimWalk = 526,
        FlySwimWalk = 527,
        SwimWalkBackwards = 528,
        FlySwimWalkBackwards = 529,
        SwimSprint = 530,
        FlySwimSprint = 531,
        MountSwimIdle = 532,
        FlyMountSwimIdle = 533,
        MountSwimBackwards = 534,
        FlyMountSwimBackwards = 535,
        MountSwimLeft = 536,
        FlyMountSwimLeft = 537,
        MountSwimRight = 538,
        FlyMountSwimRight = 539,
        MountSwimRun = 540,
        FlyMountSwimRun = 541,
        MountSwimSprint = 542,
        FlyMountSwimSprint = 543,
        MountSwimWalk = 544,
        FlyMountSwimWalk = 545,
        MountSwimWalkBackwards = 546,
        FlyMountSwimWalkBackwards = 547,
        MountFlightIdle = 548,
        FlyMountFlightIdle = 549,
        MountFlightBackwards = 550,
        FlyMountFlightBackwards = 551,
        MountFlightLeft = 552,
        FlyMountFlightLeft = 553,
        MountFlightRight = 554,
        FlyMountFlightRight = 555,
        MountFlightRun = 556,
        FlyMountFlightRun = 557,
        MountFlightSprint = 558,
        FlyMountFlightSprint = 559,
        MountFlightWalk = 560,
        FlyMountFlightWalk = 561,
        MountFlightWalkBackwards = 562,
        FlyMountFlightWalkBackwards = 563,
        MountFlightStart = 564,
        FlyMountFlightStart = 565,
        MountSwimStart = 566,
        FlyMountSwimStart = 567,
        MountSwimLand = 568,
        FlyMountSwimLand = 569,
        MountSwimLandRun = 570,
        FlyMountSwimLandRun = 571,
        MountFlightLand = 572,
        FlyMountFlightLand = 573,
        MountFlightLandRun = 574,
        FlyMountFlightLandRun = 575,
        ReadyBlowDart = 576,
        FlyReadyBlowDart = 577,
        LoadBlowDart = 578,
        FlyLoadBlowDart = 579,
        HoldBlowDart = 580,
        FlyHoldBlowDart = 581,
        AttackBlowDart = 582,
        FlyAttackBlowDart = 583,
        CarriageMount = 584,
        FlyCarriageMount = 585,
        CarriagePassengerMount = 586,
        FlyCarriagePassengerMount = 587,
        CarriageMountAttack = 588,
        FlyCarriageMountAttack = 589,
        BartenderStand = 590,
        FlyBartenderStand = 591,
        BartenderWalk = 592,
        FlyBartenderWalk = 593,
        BartenderRun = 594,
        FlyBartenderRun = 595,
        BartenderShuffleLeft = 596,
        FlyBartenderShuffleLeft = 597,
        BartenderShuffleRight = 598,
        FlyBartenderShuffleRight = 599,
        BartenderEmoteTalk = 600,
        FlyBartenderEmoteTalk = 601,
        BartenderEmotePoint = 602,
        FlyBartenderEmotePoint = 603,
        BarmaidStand = 604,
        FlyBarmaidStand = 605,
        BarmaidWalk = 606,
        FlyBarmaidWalk = 607,
        BarmaidRun = 608,
        FlyBarmaidRun = 609,
        BarmaidShuffleLeft = 610,
        FlyBarmaidShuffleLeft = 611,
        BarmaidShuffleRight = 612,
        FlyBarmaidShuffleRight = 613,
        BarmaidEmoteTalk = 614,
        FlyBarmaidEmoteTalk = 615,
        BarmaidEmotePoint = 616,
        FlyBarmaidEmotePoint = 617,
        MountSelfIdle = 618,
        FlyMountSelfIdle = 619,
        MountSelfWalk = 620,
        FlyMountSelfWalk = 621,
        MountSelfRun = 622,
        FlyMountSelfRun = 623,
        MountSelfSprint = 624,
        FlyMountSelfSprint = 625,
        MountSelfRunLeft = 626,
        FlyMountSelfRunLeft = 627,
        MountSelfRunRight = 628,
        FlyMountSelfRunRight = 629,
        MountSelfShuffleLeft = 630,
        FlyMountSelfShuffleLeft = 631,
        MountSelfShuffleRight = 632,
        FlyMountSelfShuffleRight = 633,
        MountSelfWalkBackwards = 634,
        FlyMountSelfWalkBackwards = 635,
        MountSelfSpecial = 636,
        FlyMountSelfSpecial = 637,
        MountSelfJump = 638,
        FlyMountSelfJump = 639,
        MountSelfJumpStart = 640,
        FlyMountSelfJumpStart = 641,
        MountSelfJumpEnd = 642,
        FlyMountSelfJumpEnd = 643,
        MountSelfJumpLandRun = 644,
        FlyMountSelfJumpLandRun = 645,
        MountSelfStart = 646,
        FlyMountSelfStart = 647,
        MountSelfFall = 648,
        FlyMountSelfFall = 649,
        Stormstrike = 650,
        FlyStormstrike = 651,
        ReadyJoustNoSheathe = 652,
        FlyReadyJoustNoSheathe = 653,
        Slam = 654,
        FlySlam = 655,
        DeathStrike = 656,
        FlyDeathStrike = 657,
        SwimAttackUnarmed = 658,
        FlySwimAttackUnarmed = 659,
        SpinningKick = 660,
        FlySpinningKick = 661,
        RoundHouseKick = 662,
        FlyRoundHouseKick = 663,
        RollStart = 664,
        FlyRollStart = 665,
        Roll = 666,
        FlyRoll = 667,
        RollEnd = 668,
        FlyRollEnd = 669,
        PalmStrike = 670,
        FlyPalmStrike = 671,
        MonkOffenseAttackUnarmed = 672,
        FlyMonkOffenseAttackUnarmed = 673,
        MonkOffenseAttackUnarmedOff = 674,
        FlyMonkOffenseAttackUnarmedOff = 675,
        MonkOffenseParryUnarmed = 676,
        FlyMonkOffenseParryUnarmed = 677,
        MonkOffenseReadyUnarmed = 678,
        FlyMonkOffenseReadyUnarmed = 679,
        MonkOffenseSpecialUnarmed = 680,
        FlyMonkOffenseSpecialUnarmed = 681,
        MonkDefenseAttackUnarmed = 682,
        FlyMonkDefenseAttackUnarmed = 683,
        MonkDefenseAttackUnarmedOff = 684,
        FlyMonkDefenseAttackUnarmedOff = 685,
        MonkDefenseParryUnarmed = 686,
        FlyMonkDefenseParryUnarmed = 687,
        MonkDefenseReadyUnarmed = 688,
        FlyMonkDefenseReadyUnarmed = 689,
        MonkDefenseSpecialUnarmed = 690,
        FlyMonkDefenseSpecialUnarmed = 691,
        MonkHealAttackUnarmed = 692,
        FlyMonkHealAttackUnarmed = 693,
        MonkHealAttackUnarmedOff = 694,
        FlyMonkHealAttackUnarmedOff = 695,
        MonkHealParryUnarmed = 696,
        FlyMonkHealParryUnarmed = 697,
        MonkHealReadyUnarmed = 698,
        FlyMonkHealReadyUnarmed = 699,
        MonkHealSpecialUnarmed = 700,
        FlyMonkHealSpecialUnarmed = 701,
        FlyingKick = 702,
        FlyFlyingKick = 703,
        FlyingKickStart = 704,
        FlyFlyingKickStart = 705,
        FlyingKickEnd = 706,
        FlyFlyingKickEnd = 707,
        CraneStart = 708,
        FlyCraneStart = 709,
        CraneLoop = 710,
        FlyCraneLoop = 711,
        CraneEnd = 712,
        FlyCraneEnd = 713,
        Despawned = 714,
        FlyDespawned = 715,
        ThousandFists = 716,
        FlyThousandFists = 717,
        MonkHealReadySpellDirected = 718,
        FlyMonkHealReadySpellDirected = 719,
        MonkHealReadySpellOmni = 720,
        FlyMonkHealReadySpellOmni = 721,
        MonkHealSpellCastDirected = 722,
        FlyMonkHealSpellCastDirected = 723,
        MonkHealSpellCastOmni = 724,
        FlyMonkHealSpellCastOmni = 725,
        MonkHealChannelCastDirected = 726,
        FlyMonkHealChannelCastDirected = 727,
        MonkHealChannelCastOmni = 728,
        FlyMonkHealChannelCastOmni = 729,
        Torpedo = 730,
        FlyTorpedo = 731,
        Meditate = 732,
        FlyMeditate = 733,
        BreathOfFire = 734,
        FlyBreathOfFire = 735,
        RisingSunKick = 736,
        FlyRisingSunKick = 737,
        GroundKick = 738,
        FlyGroundKick = 739,
        KickBack = 740,
        FlyKickBack = 741,
        PetBattleStand = 742,
        FlyPetBattleStand = 743,
        PetBattleDeath = 744,
        FlyPetBattleDeath = 745,
        PetBattleRun = 746,
        FlyPetBattleRun = 747,
        PetBattleWound = 748,
        FlyPetBattleWound = 749,
        PetBattleAttack = 750,
        FlyPetBattleAttack = 751,
        PetBattleReadySpell = 752,
        FlyPetBattleReadySpell = 753,
        PetBattleSpellCast = 754,
        FlyPetBattleSpellCast = 755,
        PetBattleCustom0 = 756,
        FlyPetBattleCustom0 = 757,
        PetBattleCustom1 = 758,
        FlyPetBattleCustom1 = 759,
        PetBattleCustom2 = 760,
        FlyPetBattleCustom2 = 761,
        PetBattleCustom3 = 762,
        FlyPetBattleCustom3 = 763,
        PetBattleVictory = 764,
        FlyPetBattleVictory = 765,
        PetBattleLoss = 766,
        FlyPetBattleLoss = 767,
        PetBattleStun = 768,
        FlyPetBattleStun = 769,
        PetBattleDead = 770,
        FlyPetBattleDead = 771,
        PetBattleFreeze = 772,
        FlyPetBattleFreeze = 773,
        MonkOffenseAttackWeapon = 774,
        FlyMonkOffenseAttackWeapon = 775,
        BarTendEmoteWave = 776,
        FlyBarTendEmoteWave = 777,
        BarServerEmoteTalk = 778,
        FlyBarServerEmoteTalk = 779,
        BarServerEmoteWave = 780,
        FlyBarServerEmoteWave = 781,
        BarServerPourDrinks = 782,
        FlyBarServerPourDrinks = 783,
        BarServerPickup = 784,
        FlyBarServerPickup = 785,
        BarServerPutDown = 786,
        FlyBarServerPutDown = 787,
        BarSweepStand = 788,
        FlyBarSweepStand = 789,
        BarPatronSit = 790,
        FlyBarPatronSit = 791,
        BarPatronSitEmoteTalk = 792,
        FlyBarPatronSitEmoteTalk = 793,
        BarPatronStand = 794,
        FlyBarPatronStand = 795,
        BarPatronStandEmoteTalk = 796,
        FlyBarPatronStandEmoteTalk = 797,
        BarPatronStandEmotePoint = 798,
        FlyBarPatronStandEmotePoint = 799,
        CarrionSwarm = 800,
        FlyCarrionSwarm = 801,
        WheelLoop = 802,
        FlyWheelLoop = 803,
        StandCharacterCreate = 804,
        FlyStandCharacterCreate = 805,
        MountChopper = 806,
        FlyMountChopper = 807,
        FacePose = 808,
        FlyFacePose = 809,
        WarriorColossusSmash = 810,
        FlyWarriorColossusSmash = 811,
        WarriorMortalStrike = 812,
        FlyWarriorMortalStrike = 813,
        WarriorWhirlwind = 814,
        FlyWarriorWhirlwind = 815,
        WarriorCharge = 816,
        FlyWarriorCharge = 817,
        WarriorChargeStart = 818,
        FlyWarriorChargeStart = 819,
        WarriorChargeEnd = 820,
        FlyWarriorChargeEnd = 821
    }

    public enum AreaFlags
    {
        Snow = 0x01,                // Snow (Only Dun Morogh, Naxxramas, Razorfen Downs And Winterspring)
        Unk1 = 0x02,                // Razorfen Downs, Naxxramas And Acherus: The Ebon Hold (3.3.5a)
        Unk2 = 0x04,                // Only Used For Areas On Map 571 (Development Before)
        SlaveCapital = 0x08,                // City And City Subsones
        Unk3 = 0x10,                // Can'T Find Common Meaning
        SlaveCapital2 = 0x20,                // Slave Capital City Flag?
        AllowDuels = 0x40,                // Allow To Duel Here
        Arena = 0x80,                // Arena, Both Instanced And World Arenas
        Capital = 0x100,                // Main Capital City Flag
        City = 0x200,                // Only For One Zone Named "City" (Where It Located?)
        Outland = 0x400,                // Expansion Zones? (Only Eye Of The Storm Not Have This Flag, But Have 0x00004000 Flag)
        Sanctuary = 0x800,                // Sanctuary Area (Pvp Disabled)
        NeedFly = 0x1000,                // Unknown
        Unused1 = 0x2000,                // Unused In 3.3.5a
        Outland2 = 0x4000,                // Expansion Zones? (Only Circle Of Blood Arena Not Have This Flag, But Have 0x00000400 Flag)
        OutdoorPvp = 0x8000,                // Pvp Objective Area? (Death'S Door Also Has This Flag Although It'S No Pvp Object Area)
        ArenaInstance = 0x10000,                // Used By Instanced Arenas Only
        Unused2 = 0x20000,                // Unused In 3.3.5a
        ContestedArea = 0x40000,                // On Pvp Servers These Areas Are Considered Contested, Even Though The Zone It Is Contained In Is A Horde/Alliance Territory.
        Unk6 = 0x80000,                // Valgarde And Acherus: The Ebon Hold
        Lowlevel = 0x100000,                // Used For Some Starting Areas With AreaLevel <= 15
        Town = 0x200000,                // Small Towns With Inn
        RestZoneHorde = 0x400000,                // Warsong Hold, Acherus: The Ebon Hold, New Agamand Inn, Vengeance Landing Inn, Sunreaver Pavilion (Something To Do With Team?)
        RestZoneAlliance = 0x800000,                // Valgarde, Acherus: The Ebon Hold, Westguard Inn, Silver Covenant Pavilion (Something To Do With Team?)
        Wintergrasp = 0x1000000,                // Wintergrasp And It'S Subzones
        Inside = 0x2000000,                // Used For Determinating Spell Related Inside/Outside Questions In Map.Isoutdoors
        Outside = 0x4000000,                // Used For Determinating Spell Related Inside/Outside Questions In Map.Isoutdoors
        CanHearthAndResurrect = 0x8000000,                // Can Hearth And Resurrect From Area
        NoFlyZone = 0x20000000,                // Marks Zones Where You Cannot Fly
        Unk9 = 0x40000000,
    }

    public enum ArtifactCategory
    {
        Primary = 1,
        Fishing = 2
    }

    public enum ArtifactPowerFlag : byte
    {
        Gold = 0x01,
        NoLinkRequired = 0x02,
        Final = 0x04,
        ScalesWithNumPowers = 0x08,
        DontCountFirstBonusRank = 0x10,
        MaxRankWithTier = 0x20,

        First = NoLinkRequired | DontCountFirstBonusRank,
    }

    public enum BattlegroundBracketId                                  // bracketId for level ranges
    {
        First = 0,
        Last = 12,
        Max
    }

    public enum CharBaseSectionVariation : byte
    {
        Skin = 0,
        Face = 1,
        FacialHair = 2,
        Hair = 3,
        Underwear = 4,
        CustomDisplay1 = 5,
        CustomDisplay2 = 6,
        CustomDisplay3 = 7,

        Max
    }

    public enum CharSectionFlags
    {
        Player = 0x01,
        DeathKnight = 0x04,
        DemonHunter = 0x20
    }

    public enum CharSectionType
    {
        SkinLowRes = 0,
        FaceLowRes = 1,
        FacialHairLowRes = 2,
        HairLowRes = 3,
        UnderwearLowRes = 4,
        Skin = 5,
        Face = 6,
        FacialHair = 7,
        Hair = 8,
        Underwear = 9,
        CustomDisplay1LowRes = 10,
        CustomDisplay1 = 11,
        CustomDisplay2LowRes = 12,
        CustomDisplay2 = 13,
        CustomDisplay3LowRes = 14,
        CustomDisplay3 = 15,

        Max
    }

    public enum ChrSpecializationFlag
    {
        Caster = 0x01,
        Ranged = 0x02,
        Melee = 0x04,
        Unknown = 0x08,
        DualWieldTwoHanded = 0x10,     // Used For Cunitdisplay::Setsheatheinvertedfordualwield
        PetOverrideSpec = 0x20,
        Recommended = 0x40,
    }

    public enum Curves
    {
        ArtifactRelicItemLevelBonus = 1718
    }

    public enum Emote
    {
        OneshotNone = 0,
        OneshotTalk = 1,
        OneshotBow = 2,
        OneshotWave = 3,
        OneshotCheer = 4,
        OneshotExclamation = 5,
        OneshotQuestion = 6,
        OneshotEat = 7,
        StateDance = 10,
        OneshotLaugh = 11,
        StateSleep = 12,
        StateSit = 13,
        OneshotRude = 14,
        OneshotRoar = 15,
        OneshotKneel = 16,
        OneshotKiss = 17,
        OneshotCry = 18,
        OneshotChicken = 19,
        OneshotBeg = 20,
        OneshotApplaud = 21,
        OneshotShout = 22,
        OneshotFlex = 23,
        OneshotShy = 24,
        OneshotPoint = 25,
        StateStand = 26,
        StateReadyUnarmed = 27,
        StateWorkSheathed = 28,
        StatePoint = 29,
        StateNone = 30,
        OneshotWound = 33,
        OneshotWoundCritical = 34,
        OneshotAttackUnarmed = 35,
        OneshotAttack1h = 36,
        OneshotAttack2htight = 37,
        OneshotAttack2hLoose = 38,
        OneshotParryUnarmed = 39,
        OneshotParryShield = 43,
        OneshotReadyUnarmed = 44,
        OneshotReady1h = 45,
        OneshotReadyBow = 48,
        OneshotSpellPrecast = 50,
        OneshotSpellCast = 51,
        OneshotBattleRoar = 53,
        OneshotSpecialattack1h = 54,
        OneshotKick = 60,
        OneshotAttackThrown = 61,
        StateStun = 64,
        StateDead = 65,
        OneshotSalute = 66,
        StateKneel = 68,
        StateUseStanding = 69,
        OneshotWaveNoSheathe = 70,
        OneshotCheerNoSheathe = 71,
        OneshotEatNoSheathe = 92,
        StateStunNoSheathe = 93,
        OneshotDance = 94,
        OneshotSaluteNoSheath = 113,
        StateUseStandingNoSheathe = 133,
        OneshotLaughNoSheathe = 153,
        StateWork = 173,
        StateSpellPrecast = 193,
        OneshotReadyRifle = 213,
        StateReadyRifle = 214,
        StateWorkMining = 233,
        StateWorkChopwood = 234,
        StateApplaud = 253,
        OneshotLiftoff = 254,
        OneshotYes = 273,
        OneshotNo = 274,
        OneshotTrain = 275,
        OneshotLand = 293,
        StateAtEase = 313,
        StateReady1h = 333,
        StateSpellKneelStart = 353,
        StateSubmerged = 373,
        OneshotSubmerge = 374,
        StateReady2h = 375,
        StateReadyBow = 376,
        OneshotMountSpecial = 377,
        StateTalk = 378,
        StateFishing = 379,
        OneshotFishing = 380,
        OneshotLoot = 381,
        StateWhirlwind = 382,
        StateDrowned = 383,
        StateHoldBow = 384,
        StateHoldRifle = 385,
        StateHoldThrown = 386,
        OneshotDrown = 387,
        OneshotStomp = 388,
        OneshotAttackOff = 389,
        OneshotAttackOffPierce = 390,
        StateRoar = 391,
        StateLaugh = 392,
        OneshotCreatureSpecial = 393,
        OneshotJumplandrun = 394,
        OneshotJumpend = 395,
        OneshotTalkNoSheathe = 396,
        OneshotPointNoSheathe = 397,
        StateCannibalize = 398,
        OneshotJumpstart = 399,
        StateDancespecial = 400,
        OneshotDancespecial = 401,
        OneshotCustomSpell01 = 402,
        OneshotCustomSpell02 = 403,
        OneshotCustomSpell03 = 404,
        OneshotCustomSpell04 = 405,
        OneshotCustomSpell05 = 406,
        OneshotCustomSpell06 = 407,
        OneshotCustomSpell07 = 408,
        OneshotCustomSpell08 = 409,
        OneshotCustomSpell09 = 410,
        OneshotCustomSpell10 = 411,
        StateExclaim = 412,
        StateDanceCustom = 413,
        StateSitChairMed = 415,
        StateCustomSpell01 = 416,
        StateCustomSpell02 = 417,
        StateEat = 418,
        StateCustomSpell04 = 419,
        StateCustomSpell03 = 420,
        StateCustomSpell05 = 421,
        StateSpelleffectHold = 422,
        StateEatNoSheathe = 423,
        StateMount = 424,
        StateReady2hl = 425,
        StateSitChairHigh = 426,
        StateFall = 427,
        StateLoot = 428,
        StateSubmergedNew = 429,
        OneshotCower = 430,
        StateCower = 431,
        OneshotUseStanding = 432,
        StateStealthStand = 433,
        OneshotOmnicastGhoul = 434,
        OneshotAttackBow = 435,
        OneshotAttackRifle = 436,
        StateSwimIdle = 437,
        StateAttackUnarmed = 438,
        OneshotSpellCastWSound = 439,
        OneshotDodge = 440,
        OneshotParry1h = 441,
        OneshotParry2h = 442,
        OneshotParry2hl = 443,
        StateFlyfall = 444,
        OneshotFlydeath = 445,
        StateFlyFall = 446,
        OneshotFlySitGroundDown = 447,
        OneshotFlySitGroundUp = 448,
        OneshotEmerge = 449,
        OneshotDragonSpit = 450,
        StateSpecialUnarmed = 451,
        OneshotFlygrab = 452,
        StateFlygrabclosed = 453,
        OneshotFlygrabthrown = 454,
        StateFlySitGround = 455,
        StateWalkBackwards = 456,
        OneshotFlytalk = 457,
        OneshotFlyattack1h = 458,
        StateCustomSpell08 = 459,
        OneshotFlyDragonSpit = 460,
        StateSitChairLow = 461,
        OneshotStun = 462,
        OneshotSpellCastOmni = 463,
        StateReadyThrown = 465,
        OneshotWorkChopwood = 466,
        OneshotWorkMining = 467,
        StateSpellChannelOmni = 468,
        StateSpellChannelDirected = 469,
        StandStateNone = 470,
        StateReadyjoust = 471,
        StateStrangulate = 472,
        StateStrangulate2 = 473,
        StateReadySpellOmni = 474,
        StateHoldJoust = 475,
        OneshotCryJaina = 476,
        OneshotSpecialUnarmed = 477,
        StateDanceNosheathe = 478,
        OneshotSniff = 479,
        OneshotDragonstomp = 480,
        OneshotKnockdown = 482,
        StateRead = 483,
        OneshotFlyemotetalk = 485,
        StateReadAllowmovement = 492,
        StateCustomSpell06 = 498,
        StateCustomSpell07 = 499,
        StateCustomSpell082 = 500,
        StateCustomSpell09 = 501,
        StateCustomSpell10 = 502,
        StateReady1hAllowMovement = 505,
        StateReady2hAllowMovement = 506,
        OneshotMonkoffenseAttackunarmed = 507,
        OneshotMonkoffenseSpecialunarmed = 508,
        OneshotMonkoffenseParryunarmed = 509,
        StateMonkoffenseReadyunarmed = 510,
        OneshotPalmstrike = 511,
        StateCrane = 512,
        OneshotOpen = 517,
        StateReadChristmas = 518,
        OneshotFlyattack2hl = 526,
        OneshotFlyattackthrown = 527,
        StateFlyreadyspelldirected = 528,
        StateFlyReady1h = 531,
        StateMeditate = 533,
        StateFlyReady2hl = 534,
        OneshotToground = 535,
        OneshotTofly = 536,
        StateAttackthrown = 537,
        StateSpellChannelDirectedNosound = 538,
        OneshotWork = 539,
        StateReadyunarmedNosound = 540,
        OneshotMonkoffenseAttackunarmedoff = 543,
        ReclinedMountPassenger = 546,
        OneshotQuestion_2 = 547,
        OneshotSpellChannelDirectedNosound = 549,
        StateKneel2 = 550,
        OneshotFlyattackunarmed = 551,
        OneshotFlycombatwound = 552,
        OneshotMountselfspecial = 553,
        OneshotAttackunarmedNosound = 554,
        StateWoundcriticalDoesntWork = 555,
        OneshotAttack1hNoSound = 556,
        StateMountSelfIdle = 557,
        OneshotWalk = 558,
        StateOpened = 559,
        StateCustomspell03 = 564,
        OneshotBreathoffire = 565,
        StateAttack1h = 567,
        StateWorkChopwood2 = 568,
        StateUsestandingLoop = 569,
        StateUsestanding = 572,
        OneshotSheath = 573,
        OneshotLaughNoSound = 574,
        ReclinedMount = 575,
        OneshotAttack1h2 = 577,
        StateCryNosound = 578,
        OneshotCryNosound = 579,
        OneshotCombatcritical = 584,
        StateTrain = 585,
        StateWorkChopwoodLumberAxe = 586,
        OneshotSpecialattack2h = 587,
        StateReadAndTalk = 588,
        OneshotStandVar1 = 589,
        RexxarStranglesGoblin = 590,
        OneshotStandVar2 = 591,
        OneshotDeath = 592,
        StateTalkonce = 595,
        StateAttack2h = 596,
        StateSitGround = 598,
        StateWorkChopwood3 = 599,
        StateCustomspell01 = 601,
        OneshotCombatwound = 602,
        OneshotTalkExclamation = 603,
        OneshotQuestion2 = 604,
        StateCry = 605,
        StateUsestandingLoop2 = 606,
        StateWorkSmith = 613,
        StateWorkChopwood4 = 614,
        StateCustomspell02 = 615,
        StateReadAndSit = 616,
        StateParryUnarmed = 619,
        StateBlockShield = 620,
        StateSitGround2 = 621
    }

    public enum GlyphSlotType
    {
        Major = 0,
        Minor = 1,
        Prime = 2
    }

    public enum ItemSetFlags
    {
        LegacyInactive = 0x01,
    }

    public enum ItemSpecStat : byte
    {
        Intellect = 0,
        Agility = 1,
        Strength = 2,
        Spirit = 3,
        Hit = 4,
        Dodge = 5,
        Parry = 6,
        OneHandedAxe = 7,
        TwoHandedAxe = 8,
        OneHandedSword = 9,
        TwoHandedSword = 10,
        OneHandedMace = 11,
        TwoHandedMace = 12,
        Dagger = 13,
        FistWeapon = 14,
        Gun = 15,
        Bow = 16,
        Crossbow = 17,
        Staff = 18,
        Polearm = 19,
        Thrown = 20,
        Wand = 21,
        Shield = 22,
        Relic = 23,
        Crit = 24,
        Haste = 25,
        BonusArmor = 26,
        Cloak = 27,
        Warglaives = 28,
        RelicIron = 29,
        RelicBlood = 30,
        RelicShadow = 31,
        RelicFel = 32,
        RelicArcane = 33,
        RelicFrost = 34,
        RelicFire = 35,
        RelicWater = 36,
        RelicLife = 37,
        RelicWind = 38,
        RelicHoly = 39,

        None = 40
    }

    public enum LockKeyType
    {
        None = 0,
        Item = 1,
        Skill = 2
    }

    public enum LockType
    {
        Lockpicking = 1,
        Herbalism = 2,
        Mining = 3,
        DisarmTrap = 4,
        Open = 5,
        Treasure = 6,
        CalcifiedElvenGems = 7,
        Close = 8,
        ArmTrap = 9,
        QuickOpen = 10,
        QuickClose = 11,
        OpenTinkering = 12,
        OpenKneeling = 13,
        OpenAttacking = 14,
        Gahzridian = 15,
        Blasting = 16,
        PvpOpen = 17,
        PvpClose = 18,
        Fishing = 19,
        Inscription = 20,
        OpenFromVehicle = 21,
        Archaeology = 22,
        PvpOpenFast = 23,
        LumberMill = 28,
        Skinning = 29,
        AncientMana = 30,
        Warboard = 31,
        ClassicHerbalism = 32,
        OutlandHerbalism = 33,
        NorthrendHerbalism = 34,
        CataclysmHerbalism = 35,
        PandariaHerbalism = 36,
        DraenorHerbalism = 37,
        LegionHerbalism = 38,
        KulTiranHerbalism = 39,
        ClassicMining = 40,
        OutlandMining = 41,
        NorthrendMining = 42,
        CataclysmMining = 43,
        PandariaMining = 44,
        DraenorMining = 45,
        LegionMining = 46,
        KulTiranMining = 47,
        Skinning2 = 48
    }

    public enum MapTypes : byte
    {
        Common = 0,
        Instance = 1,
        Raid = 2,
        Battleground = 3,
        Arena = 4,
        Scenario = 5
    }

    public enum MapDifficultyFlags : byte
    {
        CannotExtend = 0x10
    }

    public enum AreaMountFlags
    {
        GroundAllowed = 0x1,
        FlyingAllowed = 0x2,
        FloatAllowed = 0x4,
        UnderwaterAllowed = 0x8
    }

    public enum MountCapabilityFlags : byte
    {
        Ground = 0x1,
        Flying = 0x2,
        Float = 0x4,
        Underwater = 0x8,
        IgnoreRestrictions = 0x20
    }

    public enum MountFlags : ushort
    {
        CanPitch = 0x4,                    // client checks MOVEMENTFLAG2_FULL_SPEED_PITCHING
        CanSwim = 0x8,                    // client checks MOVEMENTFLAG_SWIMMING
        SelfMount = 0x02,                   // Player becomes the mount himself
        FactionSpecific = 0x04,
        PreferredSwimming = 0x10,
        PreferredWaterWalking = 0x20,
        HideIfUnknown = 0x40
    }

    public enum PhaseEntryFlags : ushort
    {
        Normal = 0x08,
        Cosmetic = 0x10,
        Personal = 0x20
    }

    // PhaseUseFlags fields in different db2s
    public  enum PhaseUseFlagsValues : byte
    {
        None = 0x0,
        AlwaysVisible = 0x1,
        Inverse = 0x2,

        All = AlwaysVisible | Inverse
    }

    public enum PrestigeLevelInfoFlags : byte
    {
        Disabled = 0x01                      // Prestige levels with this flag won't be included to calculate max prestigelevel.
    }

    public enum QuestPackageFilter : byte
    {
        LootSpecialization = 0,    // Players can select this quest reward if it matches their selected loot specialization
        Class = 1,    // Players can select this quest reward if it matches their class
        Unmatched = 2,    // Players can select this quest reward if no class/loot_spec rewards are available
        Everyone = 3     // Players can always select this quest reward
    }

    public enum ScenarioStepFlags : byte
    {
        BonusObjective = 0x1,
        HeroicOnly = 0x2
    }

    public enum SkillRaceClassInfoFlags : ushort
    {
        NoSkillupMessage = 0x2,
        AlwaysMaxValue = 0x10,
        Unlearnable = 0x20,     // Skill can be unlearned
        IncludeInSort = 0x80,     // Spells belonging to a skill with this flag will additionally compare skill ids when sorting spellbook in client
        NotTrainable = 0x100,
        MonoValue = 0x400     // Skill always has value 1
    }

    public enum SpellCategoryFlags : sbyte
    {
        CooldownScalesWithWeaponSpeed = 0x01, // unused
        CooldownStartsOnEvent = 0x04,
        CooldownExpiresAtDailyReset = 0x08
    }

    public enum SpellProcsPerMinuteModType : byte
    {
        Haste = 1,
        Crit = 2,
        Class = 3,
        Spec = 4,
        Race = 5,
        ItemLevel = 6,
        Battleground = 7
    }

    public enum SpellShapeshiftFormFlags
    {
        IsNotAShapeshift = 0x0001,
        CannotCancel = 0x0002,   // Player Cannot Cancel The Aura Giving This Shapeshift
        CanInteract = 0x0008,   // If The Form Does Not Have IsNotAShapeshift Then This Flag Must Be Present To Allow Npc Interaction
        CanEquipItems = 0x0040,   // If The Form Does Not Have IsNotAShapeshift Then This Flag Allows Equipping Items Without ItemFlagUsableWhenShapeshifted
        CanUseItems = 0x0080,   // If The Form Does Not Have IsNotAShapeshift Then This Flag Allows Using Items Without ItemFlagUsableWhenShapeshifted
        CanAutoUnshift = 0x0100,   // Clientside
        PreventLfgTeleport = 0x0200,
        PreventUsingOwnSkills = 0x0400,   // Prevents Using Spells That Don'T Have Any Shapeshift Requirement
        PreventEmoteSounds = 0x1000a
    }

    public enum SummonPropFlags
    {
        None = 0x00000000,          // 1342 Spells In 3.0.3
        Unk1 = 0x00000001,          // 75 Spells In 3.0.3, Something Unfriendly
        Unk2 = 0x00000002,          // 616 Spells In 3.0.3, Something Friendly
        Unk3 = 0x00000004,          // 22 Spells In 3.0.3, No Idea...
        Unk4 = 0x00000008,          // 49 Spells In 3.0.3, Some Mounts
        PersonalSpawn = 0x00000010,          // Personal Spawn (Creature Visible Only By Summoner)
        Unk6 = 0x00000020,          // 0 Spells In 3.3.5, Unused
        Unk7 = 0x00000040,          // 12 Spells In 3.0.3, No Idea
        Unk8 = 0x00000080,          // 4 Spells In 3.0.3, No Idea
        Unk9 = 0x00000100,          // 51 Spells In 3.0.3, No Idea, Many Quest Related
        Unk10 = 0x00000200,          // 51 Spells In 3.0.3, Something Defensive
        Unk11 = 0x00000400,          // 3 Spells, Requires Something Near?
        Unk12 = 0x00000800,          // 30 Spells In 3.0.3, No Idea
        Unk13 = 0x00001000,          // Lightwell, Jeeves, Gnomish Alarm-O-Bot, Build Vehicles(Wintergrasp)
        Unk14 = 0x00002000,          // Guides, Player Follows
        Unk15 = 0x00004000,          // Force Of Nature, Shadowfiend, Feral Spirit, Summon Water Elemental
        Unk16 = 0x00008000,          // Light/Dark Bullet, Soul/Fiery Consumption, Twisted Visage, Twilight Whelp. Phase Related?
        Unk17 = 0x00010000,
        Unk18 = 0x00020000,
        Unk19 = 0x00040000,
        Unk20 = 0x00080000,
        Unk21 = 0x00100000           // Totems
    }

    public enum TaxiNodeFlags : byte
    {
        Alliance = 0x1,
        Horde = 0x2,
        UseFavoriteMount = 0x10
    }

    public enum TaxiPathNodeFlags : byte
    {
        Teleport = 0x1,
        Stop = 0x2
    }

    public enum TextEmotes
    {
        Agree = 1,
        Amaze = 2,
        Angry = 3,
        Apologize = 4,
        Applaud = 5,
        Bashful = 6,
        Beckon = 7,
        Beg = 8,
        Bite = 9,
        Bleed = 10,
        Blink = 11,
        Blush = 12,
        Bonk = 13,
        Bored = 14,
        Bounce = 15,
        Brb = 16,
        Bow = 17,
        Burp = 18,
        Bye = 19,
        Cackle = 20,
        Cheer = 21,
        Chicken = 22,
        Chuckle = 23,
        Clap = 24,
        Confused = 25,
        Congratulate = 26,
        Cough = 27,
        Cower = 28,
        Crack = 29,
        Cringe = 30,
        Cry = 31,
        Curious = 32,
        Curtsey = 33,
        Dance = 34,
        Drink = 35,
        Drool = 36,
        Eat = 37,
        Eye = 38,
        Fart = 39,
        Fidget = 40,
        Flex = 41,
        Frown = 42,
        Gasp = 43,
        Gaze = 44,
        Giggle = 45,
        Glare = 46,
        Gloat = 47,
        Greet = 48,
        Grin = 49,
        Groan = 50,
        Grovel = 51,
        Guffaw = 52,
        Hail = 53,
        Happy = 54,
        Hello = 55,
        Hug = 56,
        Hungry = 57,
        Kiss = 58,
        Kneel = 59,
        Laugh = 60,
        Laydown = 61,
        Message = 62,
        Moan = 63,
        Moon = 64,
        Mourn = 65,
        No = 66,
        Nod = 67,
        Nosepick = 68,
        Panic = 69,
        Peer = 70,
        Plead = 71,
        Point = 72,
        Poke = 73,
        Pray = 74,
        Roar = 75,
        Rofl = 76,
        Rude = 77,
        Salute = 78,
        Scratch = 79,
        Sexy = 80,
        Shake = 81,
        Shout = 82,
        Shrug = 83,
        Shy = 84,
        Sigh = 85,
        Sit = 86,
        Sleep = 87,
        Snarl = 88,
        Spit = 89,
        Stare = 90,
        Surprised = 91,
        Surrender = 92,
        Talk = 93,
        Talkex = 94,
        Talkq = 95,
        Tap = 96,
        Thank = 97,
        Threaten = 98,
        Tired = 99,
        Victory = 100,
        Wave = 101,
        Welcome = 102,
        Whine = 103,
        Whistle = 104,
        Work = 105,
        Yawn = 106,
        Boggle = 107,
        Calm = 108,
        Cold = 109,
        Comfort = 110,
        Cuddle = 111,
        Duck = 112,
        Insult = 113,
        Introduce = 114,
        Jk = 115,
        Lick = 116,
        Listen = 117,
        Lost = 118,
        Mock = 119,
        Ponder = 120,
        Pounce = 121,
        Praise = 122,
        Purr = 123,
        Puzzle = 124,
        Raise = 125,
        Ready = 126,
        Shimmy = 127,
        Shiver = 128,
        Shoo = 129,
        Slap = 130,
        Smirk = 131,
        Sniff = 132,
        Snub = 133,
        Soothe = 134,
        Stink = 135,
        Taunt = 136,
        Tease = 137,
        Thirsty = 138,
        Veto = 139,
        Snicker = 140,
        Stand = 141,
        Tickle = 142,
        Violin = 143,
        Smile = 163,
        Rasp = 183,
        Pity = 203,
        Growl = 204,
        Bark = 205,
        Scared = 223,
        Flop = 224,
        Love = 225,
        Moo = 226,
        Commend = 243,
        Train = 264,
        Helpme = 303,
        Incoming = 304,
        Charge = 305,
        Flee = 306,
        Attackmytarget = 307,
        Oom = 323,
        Follow = 324,
        Wait = 325,
        Healme = 326,
        Openfire = 327,
        Flirt = 328,
        Joke = 329,
        Golfclap = 343,
        Wink = 363,
        Pat = 364,
        Serious = 365,
        MountSpecial = 366,
        Goodluck = 367,
        Blame = 368,
        Blank = 369,
        Brandish = 370,
        Breath = 371,
        Disagree = 372,
        Doubt = 373,
        Embarrass = 374,
        Encourage = 375,
        Enemy = 376,
        Eyebrow = 377,
        Toast = 378,
        Fail = 379,
        Highfive = 380,
        Absent = 381,
        Arm = 382,
        Awe = 383,
        Backpack = 384,
        Badfeeling = 385,
        Challenge = 386,
        Chug = 387,
        Ding = 389,
        Facepalm = 390,
        Faint = 391,
        Go = 392,
        Going = 393,
        Glower = 394,
        Headache = 395,
        Hiccup = 396,
        Hiss = 398,
        Holdhand = 399,
        Hurry = 401,
        Idea = 402,
        Jealous = 403,
        Luck = 404,
        Map = 405,
        Mercy = 406,
        Mutter = 407,
        Nervous = 408,
        Offer = 409,
        Pet = 410,
        Pinch = 411,
        Proud = 413,
        Promise = 414,
        Pulse = 415,
        Punch = 416,
        Pout = 417,
        Regret = 418,
        Revenge = 420,
        Rolleyes = 421,
        Ruffle = 422,
        Sad = 423,
        Scoff = 424,
        Scold = 425,
        Scowl = 426,
        Search = 427,
        Shakefist = 428,
        Shifty = 429,
        Shudder = 430,
        Signal = 431,
        Silence = 432,
        Sing = 433,
        Smack = 434,
        Sneak = 435,
        Sneeze = 436,
        Snort = 437,
        Squeal = 438,
        Stopattack = 439,
        Suspicious = 440,
        Think = 441,
        Truce = 442,
        Twiddle = 443,
        Warn = 444,
        Snap = 445,
        Charm = 446,
        Coverears = 447,
        Crossarms = 448,
        Look = 449,
        Object = 450,
        Sweat = 451,
        Yw = 453,
        Read = 456,
        Boot = 506
    }

    public enum ExpectedStatType : byte
    {
        CreatureHealth = 0,
        PlayerHealth = 1,
        CreatureAutoAttackDps = 2,
        CreatureArmor = 3,
        PlayerMana = 4,
        PlayerPrimaryStat = 5,
        PlayerSecondaryStat = 6,
        ArmorConstant = 7,
        None = 8,
        CreatureSpellDamage = 9
    }

    public enum UiMapSystem : sbyte
    {
        World = 0,
        Taxi = 1,
        Adventure = 2,
        Max = 3
    }

    public enum UiMapType
    {
        Cosmic = 0,
        World = 1,
        Continent = 2,
        Zone = 3,
        Dungeon = 4,
        Micro = 5,
        Orphan = 6
    }
}
