// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: bgs/low/pb/client/api/common/v1/message_types.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Bgs.Protocol {

  /// <summary>Holder for reflection information generated from bgs/low/pb/client/api/common/v1/message_types.proto</summary>
  public static partial class MessageTypesReflection {

    #region Descriptor
    /// <summary>File descriptor for bgs/low/pb/client/api/common/v1/message_types.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageTypesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjNiZ3MvbG93L3BiL2NsaWVudC9hcGkvY29tbW9uL3YxL21lc3NhZ2VfdHlw",
            "ZXMucHJvdG8SDGJncy5wcm90b2NvbBo1YmdzL2xvdy9wYi9jbGllbnQvYXBp",
            "L2NvbW1vbi92Mi9hdHRyaWJ1dGVfdHlwZXMucHJvdG8aN2Jncy9sb3cvcGIv",
            "Y2xpZW50L2dsb2JhbF9leHRlbnNpb25zL2ZpZWxkX29wdGlvbnMucHJvdG8i",
            "jwEKCU1lc3NhZ2VJZBINCgVlcG9jaBgBIAEoBBIQCghwb3NpdGlvbhgCIAEo",
            "BBIjCgZvcmlnaW4YAyABKA1CE4L5Kw8qDU1lc3NhZ2VPcmlnaW4SPAoTZXh0",
            "ZXJuYWxfbWVzc2FnZV9pZBgEIAEoCzIfLmJncy5wcm90b2NvbC5FeHRlcm5h",
            "bE1lc3NhZ2VJZCLiAQoRRXh0ZXJuYWxNZXNzYWdlSWQSLwoIcGxhdGZvcm0Y",
            "ASABKA1CHYL5KxkqF0V4dGVybmFsTWVzc2FnZVBsYXRmb3JtEhkKAmlkGAIg",
            "ASgJQg2K+SsJIgcKBQgBEIACEiEKCmNyZWF0b3JfaWQYAyABKAlCDYr5Kwki",
            "BwoFCAAQgAISKwoUY3JlYXRvcl9kaXNwbGF5X25hbWUYBCABKAlCDYr5Kwki",
            "BwoFCAAQgAISMQoNcGxhdGZvcm1fZGF0YRgFIAMoCzIaLmJncy5wcm90b2Nv",
            "bC52Mi5BdHRyaWJ1dGUqNAoPVHlwaW5nSW5kaWNhdG9yEhAKDFRZUElOR19T",
            "VEFSVBAAEg8KC1RZUElOR19TVE9QEAEqZAoXRXh0ZXJuYWxNZXNzYWdlUGxh",
            "dGZvcm0SIgoeRVhURVJOQUxfTUVTU0FHRV9QTEFURk9STV9OT05FEAASJQoh",
            "RVhURVJOQUxfTUVTU0FHRV9QTEFURk9STV9ESVNDT1JEEAEqYgoNTWVzc2Fn",
            "ZU9yaWdpbhIZChVNRVNTQUdFX09SSUdJTl9QTEFZRVIQABIZChVNRVNTQUdF",
            "X09SSUdJTl9TWVNURU0QARIbChdNRVNTQUdFX09SSUdJTl9FWFRFUk5BTBAC",
            "QgJIAQ=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Bgs.Protocol.V2.AttributeTypesReflection.Descriptor, global::Bgs.Protocol.FieldOptionsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Bgs.Protocol.TypingIndicator), typeof(global::Bgs.Protocol.ExternalMessagePlatform), typeof(global::Bgs.Protocol.MessageOrigin), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Bgs.Protocol.MessageId), global::Bgs.Protocol.MessageId.Parser, new[]{ "Epoch", "Position", "Origin", "ExternalMessageId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Bgs.Protocol.ExternalMessageId), global::Bgs.Protocol.ExternalMessageId.Parser, new[]{ "Platform", "Id", "CreatorId", "CreatorDisplayName", "PlatformData" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum TypingIndicator {
    [pbr::OriginalName("TYPING_START")] TypingStart = 0,
    [pbr::OriginalName("TYPING_STOP")] TypingStop = 1,
  }

  public enum ExternalMessagePlatform {
    [pbr::OriginalName("EXTERNAL_MESSAGE_PLATFORM_NONE")] None = 0,
    [pbr::OriginalName("EXTERNAL_MESSAGE_PLATFORM_DISCORD")] Discord = 1,
  }

  public enum MessageOrigin {
    [pbr::OriginalName("MESSAGE_ORIGIN_PLAYER")] Player = 0,
    [pbr::OriginalName("MESSAGE_ORIGIN_SYSTEM")] System = 1,
    [pbr::OriginalName("MESSAGE_ORIGIN_EXTERNAL")] External = 2,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MessageId : pb::IMessage<MessageId>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MessageId> _parser = new pb::MessageParser<MessageId>(() => new MessageId());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MessageId> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bgs.Protocol.MessageTypesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageId() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageId(MessageId other) : this() {
      _hasBits0 = other._hasBits0;
      epoch_ = other.epoch_;
      position_ = other.position_;
      origin_ = other.origin_;
      externalMessageId_ = other.externalMessageId_ != null ? other.externalMessageId_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageId Clone() {
      return new MessageId(this);
    }

    /// <summary>Field number for the "epoch" field.</summary>
    public const int EpochFieldNumber = 1;
    private readonly static ulong EpochDefaultValue = 0UL;

    private ulong epoch_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Epoch {
      get { if ((_hasBits0 & 1) != 0) { return epoch_; } else { return EpochDefaultValue; } }
      set {
        _hasBits0 |= 1;
        epoch_ = value;
      }
    }
    /// <summary>Gets whether the "epoch" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasEpoch {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "epoch" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearEpoch() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "position" field.</summary>
    public const int PositionFieldNumber = 2;
    private readonly static ulong PositionDefaultValue = 0UL;

    private ulong position_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Position {
      get { if ((_hasBits0 & 2) != 0) { return position_; } else { return PositionDefaultValue; } }
      set {
        _hasBits0 |= 2;
        position_ = value;
      }
    }
    /// <summary>Gets whether the "position" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPosition {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "position" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPosition() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "origin" field.</summary>
    public const int OriginFieldNumber = 3;
    private readonly static uint OriginDefaultValue = 0;

    private uint origin_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Origin {
      get { if ((_hasBits0 & 4) != 0) { return origin_; } else { return OriginDefaultValue; } }
      set {
        _hasBits0 |= 4;
        origin_ = value;
      }
    }
    /// <summary>Gets whether the "origin" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasOrigin {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "origin" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOrigin() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "external_message_id" field.</summary>
    public const int ExternalMessageIdFieldNumber = 4;
    private global::Bgs.Protocol.ExternalMessageId externalMessageId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Bgs.Protocol.ExternalMessageId ExternalMessageId {
      get { return externalMessageId_; }
      set {
        externalMessageId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MessageId);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MessageId other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Epoch != other.Epoch) return false;
      if (Position != other.Position) return false;
      if (Origin != other.Origin) return false;
      if (!object.Equals(ExternalMessageId, other.ExternalMessageId)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasEpoch) hash ^= Epoch.GetHashCode();
      if (HasPosition) hash ^= Position.GetHashCode();
      if (HasOrigin) hash ^= Origin.GetHashCode();
      if (externalMessageId_ != null) hash ^= ExternalMessageId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasEpoch) {
        output.WriteRawTag(8);
        output.WriteUInt64(Epoch);
      }
      if (HasPosition) {
        output.WriteRawTag(16);
        output.WriteUInt64(Position);
      }
      if (HasOrigin) {
        output.WriteRawTag(24);
        output.WriteUInt32(Origin);
      }
      if (externalMessageId_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ExternalMessageId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasEpoch) {
        output.WriteRawTag(8);
        output.WriteUInt64(Epoch);
      }
      if (HasPosition) {
        output.WriteRawTag(16);
        output.WriteUInt64(Position);
      }
      if (HasOrigin) {
        output.WriteRawTag(24);
        output.WriteUInt32(Origin);
      }
      if (externalMessageId_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(ExternalMessageId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasEpoch) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Epoch);
      }
      if (HasPosition) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Position);
      }
      if (HasOrigin) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Origin);
      }
      if (externalMessageId_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ExternalMessageId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MessageId other) {
      if (other == null) {
        return;
      }
      if (other.HasEpoch) {
        Epoch = other.Epoch;
      }
      if (other.HasPosition) {
        Position = other.Position;
      }
      if (other.HasOrigin) {
        Origin = other.Origin;
      }
      if (other.externalMessageId_ != null) {
        if (externalMessageId_ == null) {
          ExternalMessageId = new global::Bgs.Protocol.ExternalMessageId();
        }
        ExternalMessageId.MergeFrom(other.ExternalMessageId);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Epoch = input.ReadUInt64();
            break;
          }
          case 16: {
            Position = input.ReadUInt64();
            break;
          }
          case 24: {
            Origin = input.ReadUInt32();
            break;
          }
          case 34: {
            if (externalMessageId_ == null) {
              ExternalMessageId = new global::Bgs.Protocol.ExternalMessageId();
            }
            input.ReadMessage(ExternalMessageId);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Epoch = input.ReadUInt64();
            break;
          }
          case 16: {
            Position = input.ReadUInt64();
            break;
          }
          case 24: {
            Origin = input.ReadUInt32();
            break;
          }
          case 34: {
            if (externalMessageId_ == null) {
              ExternalMessageId = new global::Bgs.Protocol.ExternalMessageId();
            }
            input.ReadMessage(ExternalMessageId);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ExternalMessageId : pb::IMessage<ExternalMessageId>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ExternalMessageId> _parser = new pb::MessageParser<ExternalMessageId>(() => new ExternalMessageId());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ExternalMessageId> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bgs.Protocol.MessageTypesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExternalMessageId() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExternalMessageId(ExternalMessageId other) : this() {
      _hasBits0 = other._hasBits0;
      platform_ = other.platform_;
      id_ = other.id_;
      creatorId_ = other.creatorId_;
      creatorDisplayName_ = other.creatorDisplayName_;
      platformData_ = other.platformData_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ExternalMessageId Clone() {
      return new ExternalMessageId(this);
    }

    /// <summary>Field number for the "platform" field.</summary>
    public const int PlatformFieldNumber = 1;
    private readonly static uint PlatformDefaultValue = 0;

    private uint platform_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Platform {
      get { if ((_hasBits0 & 1) != 0) { return platform_; } else { return PlatformDefaultValue; } }
      set {
        _hasBits0 |= 1;
        platform_ = value;
      }
    }
    /// <summary>Gets whether the "platform" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPlatform {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "platform" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPlatform() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 2;
    private readonly static string IdDefaultValue = "";

    private string id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Id {
      get { return id_ ?? IdDefaultValue; }
      set {
        id_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasId {
      get { return id_ != null; }
    }
    /// <summary>Clears the value of the "id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearId() {
      id_ = null;
    }

    /// <summary>Field number for the "creator_id" field.</summary>
    public const int CreatorIdFieldNumber = 3;
    private readonly static string CreatorIdDefaultValue = "";

    private string creatorId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CreatorId {
      get { return creatorId_ ?? CreatorIdDefaultValue; }
      set {
        creatorId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "creator_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCreatorId {
      get { return creatorId_ != null; }
    }
    /// <summary>Clears the value of the "creator_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCreatorId() {
      creatorId_ = null;
    }

    /// <summary>Field number for the "creator_display_name" field.</summary>
    public const int CreatorDisplayNameFieldNumber = 4;
    private readonly static string CreatorDisplayNameDefaultValue = "";

    private string creatorDisplayName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CreatorDisplayName {
      get { return creatorDisplayName_ ?? CreatorDisplayNameDefaultValue; }
      set {
        creatorDisplayName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "creator_display_name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCreatorDisplayName {
      get { return creatorDisplayName_ != null; }
    }
    /// <summary>Clears the value of the "creator_display_name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCreatorDisplayName() {
      creatorDisplayName_ = null;
    }

    /// <summary>Field number for the "platform_data" field.</summary>
    public const int PlatformDataFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Bgs.Protocol.V2.Attribute> _repeated_platformData_codec
        = pb::FieldCodec.ForMessage(42, global::Bgs.Protocol.V2.Attribute.Parser);
    private readonly pbc::RepeatedField<global::Bgs.Protocol.V2.Attribute> platformData_ = new pbc::RepeatedField<global::Bgs.Protocol.V2.Attribute>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Bgs.Protocol.V2.Attribute> PlatformData {
      get { return platformData_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ExternalMessageId);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ExternalMessageId other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Platform != other.Platform) return false;
      if (Id != other.Id) return false;
      if (CreatorId != other.CreatorId) return false;
      if (CreatorDisplayName != other.CreatorDisplayName) return false;
      if(!platformData_.Equals(other.platformData_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasPlatform) hash ^= Platform.GetHashCode();
      if (HasId) hash ^= Id.GetHashCode();
      if (HasCreatorId) hash ^= CreatorId.GetHashCode();
      if (HasCreatorDisplayName) hash ^= CreatorDisplayName.GetHashCode();
      hash ^= platformData_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasPlatform) {
        output.WriteRawTag(8);
        output.WriteUInt32(Platform);
      }
      if (HasId) {
        output.WriteRawTag(18);
        output.WriteString(Id);
      }
      if (HasCreatorId) {
        output.WriteRawTag(26);
        output.WriteString(CreatorId);
      }
      if (HasCreatorDisplayName) {
        output.WriteRawTag(34);
        output.WriteString(CreatorDisplayName);
      }
      platformData_.WriteTo(output, _repeated_platformData_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasPlatform) {
        output.WriteRawTag(8);
        output.WriteUInt32(Platform);
      }
      if (HasId) {
        output.WriteRawTag(18);
        output.WriteString(Id);
      }
      if (HasCreatorId) {
        output.WriteRawTag(26);
        output.WriteString(CreatorId);
      }
      if (HasCreatorDisplayName) {
        output.WriteRawTag(34);
        output.WriteString(CreatorDisplayName);
      }
      platformData_.WriteTo(ref output, _repeated_platformData_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasPlatform) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Platform);
      }
      if (HasId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Id);
      }
      if (HasCreatorId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CreatorId);
      }
      if (HasCreatorDisplayName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CreatorDisplayName);
      }
      size += platformData_.CalculateSize(_repeated_platformData_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ExternalMessageId other) {
      if (other == null) {
        return;
      }
      if (other.HasPlatform) {
        Platform = other.Platform;
      }
      if (other.HasId) {
        Id = other.Id;
      }
      if (other.HasCreatorId) {
        CreatorId = other.CreatorId;
      }
      if (other.HasCreatorDisplayName) {
        CreatorDisplayName = other.CreatorDisplayName;
      }
      platformData_.Add(other.platformData_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Platform = input.ReadUInt32();
            break;
          }
          case 18: {
            Id = input.ReadString();
            break;
          }
          case 26: {
            CreatorId = input.ReadString();
            break;
          }
          case 34: {
            CreatorDisplayName = input.ReadString();
            break;
          }
          case 42: {
            platformData_.AddEntriesFrom(input, _repeated_platformData_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Platform = input.ReadUInt32();
            break;
          }
          case 18: {
            Id = input.ReadString();
            break;
          }
          case 26: {
            CreatorId = input.ReadString();
            break;
          }
          case 34: {
            CreatorDisplayName = input.ReadString();
            break;
          }
          case 42: {
            platformData_.AddEntriesFrom(ref input, _repeated_platformData_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
