// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: bgs/low/pb/client/api/common/v1/voice_types.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Bgs.Protocol.Voice.V1 {

  /// <summary>Holder for reflection information generated from bgs/low/pb/client/api/common/v1/voice_types.proto</summary>
  public static partial class VoiceTypesReflection {

    #region Descriptor
    /// <summary>File descriptor for bgs/low/pb/client/api/common/v1/voice_types.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static VoiceTypesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjFiZ3MvbG93L3BiL2NsaWVudC9hcGkvY29tbW9uL3YxL3ZvaWNlX3R5cGVz",
            "LnByb3RvEhViZ3MucHJvdG9jb2wudm9pY2UudjEaIWJncy9sb3cvcGIvY2xp",
            "ZW50L3JwY190eXBlcy5wcm90bxo3YmdzL2xvdy9wYi9jbGllbnQvZ2xvYmFs",
            "X2V4dGVuc2lvbnMvZmllbGRfb3B0aW9ucy5wcm90bxo5YmdzL2xvdy9wYi9j",
            "bGllbnQvZ2xvYmFsX2V4dGVuc2lvbnMvbWVzc2FnZV9vcHRpb25zLnByb3Rv",
            "GjhiZ3MvbG93L3BiL2NsaWVudC9nbG9iYWxfZXh0ZW5zaW9ucy9tZXRob2Rf",
            "b3B0aW9ucy5wcm90bxo5YmdzL2xvdy9wYi9jbGllbnQvZ2xvYmFsX2V4dGVu",
            "c2lvbnMvc2VydmljZV9vcHRpb25zLnByb3RvIpwBChBWb2ljZUNyZWRlbnRp",
            "YWxzEhgKEHZvaWNlX2FjY291bnRfaWQYASABKAkSDQoFdG9rZW4YAiABKAkS",
            "CwoDdXJsGAMgASgJEiYKCWpvaW5fdHlwZRgEIAEoDUITgvkrDyoNVm9pY2VK",
            "b2luVHlwZRIqCgttdXRlX3JlYXNvbhgFIAEoDUIVgvkrESoPVm9pY2VNdXRl",
            "UmVhc29uKjwKDVZvaWNlSm9pblR5cGUSFQoRVk9JQ0VfSk9JTl9OT1JNQUwQ",
            "ABIUChBWT0lDRV9KT0lOX01VVEVEEAEqowEKD1ZvaWNlTXV0ZVJlYXNvbhIa",
            "ChZWT0lDRV9NVVRFX1JFQVNPTl9OT05FEAASMgouVk9JQ0VfTVVURV9SRUFT",
            "T05fUEFSRU5UQUxfQ09OVFJPTF9MSVNURU5fT05MWRABEh8KG1ZPSUNFX01V",
            "VEVfUkVBU09OX1JFUVVFU1RFRBACEh8KG1ZPSUNFX01VVEVfUkVBU09OX1NR",
            "VUVMQ0hFRBADKkQKFFZvaWNlUHJvdmlkZXJWZXJzaW9uEhUKEVZPSUNFX1BS",
            "T1ZJREVSX1Y0EAASFQoRVk9JQ0VfUFJPVklERVJfVjUQAQ=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Bgs.Protocol.RpcTypesReflection.Descriptor, global::Bgs.Protocol.FieldOptionsReflection.Descriptor, global::Bgs.Protocol.MessageOptionsReflection.Descriptor, global::Bgs.Protocol.MethodOptionsReflection.Descriptor, global::Bgs.Protocol.ServiceOptionsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Bgs.Protocol.Voice.V1.VoiceJoinType), typeof(global::Bgs.Protocol.Voice.V1.VoiceMuteReason), typeof(global::Bgs.Protocol.Voice.V1.VoiceProviderVersion), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Bgs.Protocol.Voice.V1.VoiceCredentials), global::Bgs.Protocol.Voice.V1.VoiceCredentials.Parser, new[]{ "VoiceAccountId", "Token", "Url", "JoinType", "MuteReason" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum VoiceJoinType {
    [pbr::OriginalName("VOICE_JOIN_NORMAL")] VoiceJoinNormal = 0,
    [pbr::OriginalName("VOICE_JOIN_MUTED")] VoiceJoinMuted = 1,
  }

  public enum VoiceMuteReason {
    [pbr::OriginalName("VOICE_MUTE_REASON_NONE")] None = 0,
    [pbr::OriginalName("VOICE_MUTE_REASON_PARENTAL_CONTROL_LISTEN_ONLY")] ParentalControlListenOnly = 1,
    [pbr::OriginalName("VOICE_MUTE_REASON_REQUESTED")] Requested = 2,
    [pbr::OriginalName("VOICE_MUTE_REASON_SQUELCHED")] Squelched = 3,
  }

  public enum VoiceProviderVersion {
    [pbr::OriginalName("VOICE_PROVIDER_V4")] VoiceProviderV4 = 0,
    [pbr::OriginalName("VOICE_PROVIDER_V5")] VoiceProviderV5 = 1,
  }

  #endregion

  #region Messages
  public sealed partial class VoiceCredentials : pb::IMessage<VoiceCredentials> {
    private static readonly pb::MessageParser<VoiceCredentials> _parser = new pb::MessageParser<VoiceCredentials>(() => new VoiceCredentials());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<VoiceCredentials> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Bgs.Protocol.Voice.V1.VoiceTypesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VoiceCredentials() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VoiceCredentials(VoiceCredentials other) : this() {
      _hasBits0 = other._hasBits0;
      voiceAccountId_ = other.voiceAccountId_;
      token_ = other.token_;
      url_ = other.url_;
      joinType_ = other.joinType_;
      muteReason_ = other.muteReason_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VoiceCredentials Clone() {
      return new VoiceCredentials(this);
    }

    /// <summary>Field number for the "voice_account_id" field.</summary>
    public const int VoiceAccountIdFieldNumber = 1;
    private readonly static string VoiceAccountIdDefaultValue = "";

    private string voiceAccountId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string VoiceAccountId {
      get { return voiceAccountId_ ?? VoiceAccountIdDefaultValue; }
      set {
        voiceAccountId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "voice_account_id" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasVoiceAccountId {
      get { return voiceAccountId_ != null; }
    }
    /// <summary>Clears the value of the "voice_account_id" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearVoiceAccountId() {
      voiceAccountId_ = null;
    }

    /// <summary>Field number for the "token" field.</summary>
    public const int TokenFieldNumber = 2;
    private readonly static string TokenDefaultValue = "";

    private string token_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Token {
      get { return token_ ?? TokenDefaultValue; }
      set {
        token_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "token" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasToken {
      get { return token_ != null; }
    }
    /// <summary>Clears the value of the "token" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearToken() {
      token_ = null;
    }

    /// <summary>Field number for the "url" field.</summary>
    public const int UrlFieldNumber = 3;
    private readonly static string UrlDefaultValue = "";

    private string url_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Url {
      get { return url_ ?? UrlDefaultValue; }
      set {
        url_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "url" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasUrl {
      get { return url_ != null; }
    }
    /// <summary>Clears the value of the "url" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearUrl() {
      url_ = null;
    }

    /// <summary>Field number for the "join_type" field.</summary>
    public const int JoinTypeFieldNumber = 4;
    private readonly static uint JoinTypeDefaultValue = 0;

    private uint joinType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint JoinType {
      get { if ((_hasBits0 & 1) != 0) { return joinType_; } else { return JoinTypeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        joinType_ = value;
      }
    }
    /// <summary>Gets whether the "join_type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasJoinType {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "join_type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearJoinType() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "mute_reason" field.</summary>
    public const int MuteReasonFieldNumber = 5;
    private readonly static uint MuteReasonDefaultValue = 0;

    private uint muteReason_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint MuteReason {
      get { if ((_hasBits0 & 2) != 0) { return muteReason_; } else { return MuteReasonDefaultValue; } }
      set {
        _hasBits0 |= 2;
        muteReason_ = value;
      }
    }
    /// <summary>Gets whether the "mute_reason" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool HasMuteReason {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "mute_reason" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMuteReason() {
      _hasBits0 &= ~2;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as VoiceCredentials);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(VoiceCredentials other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (VoiceAccountId != other.VoiceAccountId) return false;
      if (Token != other.Token) return false;
      if (Url != other.Url) return false;
      if (JoinType != other.JoinType) return false;
      if (MuteReason != other.MuteReason) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (HasVoiceAccountId) hash ^= VoiceAccountId.GetHashCode();
      if (HasToken) hash ^= Token.GetHashCode();
      if (HasUrl) hash ^= Url.GetHashCode();
      if (HasJoinType) hash ^= JoinType.GetHashCode();
      if (HasMuteReason) hash ^= MuteReason.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (HasVoiceAccountId) {
        output.WriteRawTag(10);
        output.WriteString(VoiceAccountId);
      }
      if (HasToken) {
        output.WriteRawTag(18);
        output.WriteString(Token);
      }
      if (HasUrl) {
        output.WriteRawTag(26);
        output.WriteString(Url);
      }
      if (HasJoinType) {
        output.WriteRawTag(32);
        output.WriteUInt32(JoinType);
      }
      if (HasMuteReason) {
        output.WriteRawTag(40);
        output.WriteUInt32(MuteReason);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (HasVoiceAccountId) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(VoiceAccountId);
      }
      if (HasToken) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Token);
      }
      if (HasUrl) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Url);
      }
      if (HasJoinType) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(JoinType);
      }
      if (HasMuteReason) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MuteReason);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(VoiceCredentials other) {
      if (other == null) {
        return;
      }
      if (other.HasVoiceAccountId) {
        VoiceAccountId = other.VoiceAccountId;
      }
      if (other.HasToken) {
        Token = other.Token;
      }
      if (other.HasUrl) {
        Url = other.Url;
      }
      if (other.HasJoinType) {
        JoinType = other.JoinType;
      }
      if (other.HasMuteReason) {
        MuteReason = other.MuteReason;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            VoiceAccountId = input.ReadString();
            break;
          }
          case 18: {
            Token = input.ReadString();
            break;
          }
          case 26: {
            Url = input.ReadString();
            break;
          }
          case 32: {
            JoinType = input.ReadUInt32();
            break;
          }
          case 40: {
            MuteReason = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
